run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports
    - misspell
    - nolintlint

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
  goimports:
    local-prefixes: github.com/gallowaysoftware/toqui

issues:
  exclude-dirs:
    - gen
