import { Platform } from "react-native";
import type { Trip, Itinerary } from "@gen/toqui/v1/trip_pb";
import { getDayColor } from "@/components/map/colors";

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");
}

function buildItineraryHTML(trip: Trip, itinerary: Itinerary): string {
  const days = itinerary.days.slice().sort((a, b) => a.dayNumber - b.dayNumber);

  const daysSections = days.map((day) => {
    const color = getDayColor(day.dayNumber);
    const items = day.items
      .slice()
      .sort((a, b) => a.orderInDay - b.orderInDay)
      .map((item) => {
        const time = item.startTime
          ? new Date(Number(item.startTime.seconds) * 1000).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
          : "";
        return `
          <div style="margin-left:16px;padding:8px 0;border-bottom:1px solid #eee;">
            <div style="display:flex;justify-content:space-between;">
              <strong>${escapeHtml(item.title)}</strong>
              ${time ? `<span style="color:#888;font-size:12px;">${escapeHtml(time)}</span>` : ""}
            </div>
            ${item.description ? `<p style="color:#666;font-size:13px;margin:4px 0 0;">${escapeHtml(item.description)}</p>` : ""}
            ${item.type ? `<span style="color:${color};font-size:11px;font-weight:600;text-transform:capitalize;">${escapeHtml(item.type)}</span>` : ""}
          </div>`;
      })
      .join("");

    return `
      <div style="margin-bottom:24px;">
        <div style="border-left:4px solid ${color};padding-left:12px;margin-bottom:8px;">
          <span style="background:${color};color:#fff;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:700;">Day ${day.dayNumber}</span>
          ${day.date ? `<span style="color:#888;font-size:13px;margin-left:8px;">${escapeHtml(day.date)}</span>` : ""}
          ${day.summary ? `<span style="color:#333;font-size:14px;margin-left:8px;">${escapeHtml(day.summary)}</span>` : ""}
        </div>
        ${items || '<p style="color:#999;font-style:italic;margin-left:16px;">No items</p>'}
      </div>`;
  }).join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; padding: 32px; color: #333; max-width: 800px; margin: 0 auto; }
    h1 { color: #e8654a; margin-bottom: 4px; }
    .meta { color: #888; font-size: 14px; margin-bottom: 24px; }
    .description { color: #666; font-size: 15px; line-height: 1.5; margin-bottom: 24px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(trip.title)}</h1>
  <div class="meta">
    ${trip.startDate && trip.endDate ? `${escapeHtml(trip.startDate)} — ${escapeHtml(trip.endDate)}` : ""}
    ${trip.destinationCountry ? ` · ${escapeHtml(trip.destinationCountry)}` : ""}
  </div>
  ${trip.description ? `<p class="description">${escapeHtml(trip.description)}</p>` : ""}
  ${daysSections || '<p style="color:#999;">No itinerary items yet.</p>'}
  <p style="color:#ccc;font-size:11px;margin-top:32px;text-align:center;">Generated by Toqui · toqui.travel</p>
</body>
</html>`;
}

export async function exportItineraryPDF(trip: Trip, itinerary: Itinerary): Promise<void> {
  const html = buildItineraryHTML(trip, itinerary);

  if (Platform.OS === "web") {
    const win = window.open("", "_blank");
    if (win) {
      win.document.write(html);
      win.document.close();
      win.print();
    }
    return;
  }

  // Native: use expo-print to generate PDF and expo-sharing to share
  const Print = await import("expo-print");
  const Sharing = await import("expo-sharing");
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: "application/pdf" });
}
