// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, trip_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, departure_location, arrival_location, num_guests)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests
`

type CreateBookingParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	TripID            pgtype.UUID        `json:"trip_id"`
	Type              string             `json:"type"`
	ConfirmationCode  pgtype.Text        `json:"confirmation_code"`
	Provider          pgtype.Text        `json:"provider"`
	Title             string             `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Location          interface{}        `json:"location"`
	Address           pgtype.Text        `json:"address"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         pgtype.Text        `json:"raw_source"`
	Source            string             `json:"source"`
	DepartureLocation pgtype.Text        `json:"departure_location"`
	ArrivalLocation   pgtype.Text        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.TripID,
		arg.Type,
		arg.ConfirmationCode,
		arg.Provider,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Address,
		arg.DetailsJson,
		arg.RawSource,
		arg.Source,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
	)
	return i, err
}

const findBookingByConfirmationCode = `-- name: FindBookingByConfirmationCode :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests FROM bookings
WHERE user_id = $1 AND trip_id = $2
  AND confirmation_code = $3
  AND confirmation_code != ''
LIMIT 1
`

type FindBookingByConfirmationCodeParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	TripID           pgtype.UUID `json:"trip_id"`
	ConfirmationCode pgtype.Text `json:"confirmation_code"`
}

func (q *Queries) FindBookingByConfirmationCode(ctx context.Context, arg FindBookingByConfirmationCodeParams) (Booking, error) {
	row := q.db.QueryRow(ctx, findBookingByConfirmationCode, arg.UserID, arg.TripID, arg.ConfirmationCode)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = $1 AND user_id = $2
`

type DeleteBookingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBooking(ctx context.Context, arg DeleteBookingParams) error {
	_, err := q.db.Exec(ctx, deleteBooking, arg.ID, arg.UserID)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests FROM bookings WHERE id = $1 AND user_id = $2
`

type GetBookingByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, arg.ID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
	)
	return i, err
}

const linkBookingToTrip = `-- name: LinkBookingToTrip :one
UPDATE bookings SET trip_id = $2
WHERE id = $1 AND user_id = $3
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests
`

type LinkBookingToTripParams struct {
	ID     uuid.UUID   `json:"id"`
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) LinkBookingToTrip(ctx context.Context, arg LinkBookingToTripParams) (Booking, error) {
	row := q.db.QueryRow(ctx, linkBookingToTrip, arg.ID, arg.TripID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
	)
	return i, err
}

const listBookingsByTrip = `-- name: ListBookingsByTrip :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests FROM bookings
WHERE trip_id = $1 AND user_id = $2
ORDER BY start_time
`

type ListBookingsByTripParams struct {
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) ListBookingsByTrip(ctx context.Context, arg ListBookingsByTripParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByTrip, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
