// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, trip_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, departure_location, arrival_location, num_guests, price_cents, currency, timezone)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type CreateBookingParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	TripID            pgtype.UUID        `json:"trip_id"`
	Type              string             `json:"type"`
	ConfirmationCode  pgtype.Text        `json:"confirmation_code"`
	Provider          pgtype.Text        `json:"provider"`
	Title             string             `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Location          interface{}        `json:"location"`
	Address           pgtype.Text        `json:"address"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         pgtype.Text        `json:"raw_source"`
	Source            string             `json:"source"`
	DepartureLocation pgtype.Text        `json:"departure_location"`
	ArrivalLocation   pgtype.Text        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
	PriceCents        pgtype.Int8        `json:"price_cents"`
	Currency          pgtype.Text        `json:"currency"`
	Timezone          pgtype.Text        `json:"timezone"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.TripID,
		arg.Type,
		arg.ConfirmationCode,
		arg.Provider,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Address,
		arg.DetailsJson,
		arg.RawSource,
		arg.Source,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
		arg.PriceCents,
		arg.Currency,
		arg.Timezone,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :execrows
DELETE FROM bookings WHERE id = $1 AND user_id = $2
`

type DeleteBookingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBooking(ctx context.Context, arg DeleteBookingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBooking, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBookingByConfirmationCode = `-- name: FindBookingByConfirmationCode :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1 AND trip_id = $2
  AND confirmation_code = $3
  AND confirmation_code != ''
LIMIT 1
`

type FindBookingByConfirmationCodeParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	TripID           pgtype.UUID `json:"trip_id"`
	ConfirmationCode pgtype.Text `json:"confirmation_code"`
}

func (q *Queries) FindBookingByConfirmationCode(ctx context.Context, arg FindBookingByConfirmationCodeParams) (Booking, error) {
	row := q.db.QueryRow(ctx, findBookingByConfirmationCode, arg.UserID, arg.TripID, arg.ConfirmationCode)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings WHERE id = $1 AND user_id = $2
`

type GetBookingByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, arg.ID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripCostSummary = `-- name: GetTripCostSummary :many
SELECT
  COALESCE(currency, 'USD') AS currency,
  SUM(price_cents) AS total_cents,
  COUNT(*) AS booking_count
FROM bookings
WHERE trip_id = $1 AND user_id = $2
  AND price_cents IS NOT NULL AND price_cents > 0
GROUP BY currency
ORDER BY total_cents DESC
`

type GetTripCostSummaryParams struct {
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

type GetTripCostSummaryRow struct {
	Currency     string `json:"currency"`
	TotalCents   int64  `json:"total_cents"`
	BookingCount int64  `json:"booking_count"`
}

func (q *Queries) GetTripCostSummary(ctx context.Context, arg GetTripCostSummaryParams) ([]GetTripCostSummaryRow, error) {
	rows, err := q.db.Query(ctx, getTripCostSummary, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripCostSummaryRow{}
	for rows.Next() {
		var i GetTripCostSummaryRow
		if err := rows.Scan(&i.Currency, &i.TotalCents, &i.BookingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkBookingToTrip = `-- name: LinkBookingToTrip :one
UPDATE bookings SET trip_id = $2
WHERE id = $1 AND user_id = $3
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type LinkBookingToTripParams struct {
	ID     uuid.UUID   `json:"id"`
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) LinkBookingToTrip(ctx context.Context, arg LinkBookingToTripParams) (Booking, error) {
	row := q.db.QueryRow(ctx, linkBookingToTrip, arg.ID, arg.TripID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByTrip = `-- name: ListBookingsByTrip :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE trip_id = $1 AND user_id = $2
ORDER BY start_time
`

type ListBookingsByTripParams struct {
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) ListBookingsByTrip(ctx context.Context, arg ListBookingsByTripParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByTrip, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
			&i.PriceCents,
			&i.Currency,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
			&i.PriceCents,
			&i.Currency,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBookings = `-- name: SearchBookings :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1
  AND (title ILIKE '%' || $2 || '%' OR provider ILIKE '%' || $2 || '%' OR confirmation_code ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3
`

type SearchBookingsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Query      pgtype.Text `json:"query"`
	MaxResults int32       `json:"max_results"`
}

func (q *Queries) SearchBookings(ctx context.Context, arg SearchBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, searchBookings, arg.UserID, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
			&i.PriceCents,
			&i.Currency,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings SET
  title = COALESCE(NULLIF($1, ''), title),
  type = COALESCE(NULLIF($2, ''), type),
  confirmation_code = COALESCE(NULLIF($3, ''), confirmation_code),
  provider = COALESCE(NULLIF($4, ''), provider),
  start_time = COALESCE($5, start_time),
  end_time = COALESCE($6, end_time),
  address = COALESCE(NULLIF($7, ''), address),
  departure_location = COALESCE(NULLIF($8, ''), departure_location),
  arrival_location = COALESCE(NULLIF($9, ''), arrival_location),
  num_guests = COALESCE($10, num_guests),
  price_cents = COALESCE($11, price_cents),
  currency = COALESCE(NULLIF($12, ''), currency),
  timezone = COALESCE(NULLIF($13, ''), timezone),
  updated_at = NOW()
WHERE id = $14 AND user_id = $15
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type UpdateBookingParams struct {
	Title             interface{}        `json:"title"`
	Type              interface{}        `json:"type"`
	ConfirmationCode  interface{}        `json:"confirmation_code"`
	Provider          interface{}        `json:"provider"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Address           interface{}        `json:"address"`
	DepartureLocation interface{}        `json:"departure_location"`
	ArrivalLocation   interface{}        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
	PriceCents        pgtype.Int8        `json:"price_cents"`
	Currency          interface{}        `json:"currency"`
	Timezone          interface{}        `json:"timezone"`
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking,
		arg.Title,
		arg.Type,
		arg.ConfirmationCode,
		arg.Provider,
		arg.StartTime,
		arg.EndTime,
		arg.Address,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
		arg.PriceCents,
		arg.Currency,
		arg.Timezone,
		arg.ID,
		arg.UserID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
