// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collaborators.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE trip_collaborators
SET user_id = $2, accepted_at = NOW()
WHERE invite_token = $1 AND accepted_at IS NULL
RETURNING id, trip_id, user_id, email, role, invite_token, invited_by, invited_at, accepted_at
`

type AcceptInviteParams struct {
	InviteToken pgtype.Text `json:"invite_token"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) (TripCollaborator, error) {
	row := q.db.QueryRow(ctx, acceptInvite, arg.InviteToken, arg.UserID)
	var i TripCollaborator
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const addCollaborator = `-- name: AddCollaborator :one
INSERT INTO trip_collaborators (trip_id, email, role, invite_token, invited_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, trip_id, user_id, email, role, invite_token, invited_by, invited_at, accepted_at
`

type AddCollaboratorParams struct {
	TripID      uuid.UUID   `json:"trip_id"`
	Email       string      `json:"email"`
	Role        string      `json:"role"`
	InviteToken pgtype.Text `json:"invite_token"`
	InvitedBy   uuid.UUID   `json:"invited_by"`
}

func (q *Queries) AddCollaborator(ctx context.Context, arg AddCollaboratorParams) (TripCollaborator, error) {
	row := q.db.QueryRow(ctx, addCollaborator,
		arg.TripID,
		arg.Email,
		arg.Role,
		arg.InviteToken,
		arg.InvitedBy,
	)
	var i TripCollaborator
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const countCollaboratorsByTrip = `-- name: CountCollaboratorsByTrip :one
SELECT COUNT(*) FROM trip_collaborators WHERE trip_id = $1
`

func (q *Queries) CountCollaboratorsByTrip(ctx context.Context, tripID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCollaboratorsByTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCollaboratorAccess = `-- name: GetCollaboratorAccess :one
SELECT id, trip_id, user_id, email, role, invite_token, invited_by, invited_at, accepted_at FROM trip_collaborators
WHERE trip_id = $1 AND user_id = $2
`

type GetCollaboratorAccessParams struct {
	TripID uuid.UUID   `json:"trip_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCollaboratorAccess(ctx context.Context, arg GetCollaboratorAccessParams) (TripCollaborator, error) {
	row := q.db.QueryRow(ctx, getCollaboratorAccess, arg.TripID, arg.UserID)
	var i TripCollaborator
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getCollaboratorByToken = `-- name: GetCollaboratorByToken :one
SELECT id, trip_id, user_id, email, role, invite_token, invited_by, invited_at, accepted_at FROM trip_collaborators
WHERE invite_token = $1
`

func (q *Queries) GetCollaboratorByToken(ctx context.Context, inviteToken pgtype.Text) (TripCollaborator, error) {
	row := q.db.QueryRow(ctx, getCollaboratorByToken, inviteToken)
	var i TripCollaborator
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getTripOwner = `-- name: GetTripOwner :one
SELECT user_id FROM trips WHERE id = $1
`

func (q *Queries) GetTripOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTripOwner, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const isAcceptedCollaboratorWithRole = `-- name: IsAcceptedCollaboratorWithRole :one
SELECT EXISTS (
  SELECT 1 FROM trip_collaborators
  WHERE trip_id = $1 AND user_id = $2 AND accepted_at IS NOT NULL AND role = $3
) AS is_collaborator
`

type IsAcceptedCollaboratorWithRoleParams struct {
	TripID uuid.UUID   `json:"trip_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) IsAcceptedCollaboratorWithRole(ctx context.Context, arg IsAcceptedCollaboratorWithRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAcceptedCollaboratorWithRole, arg.TripID, arg.UserID, arg.Role)
	var is_collaborator bool
	err := row.Scan(&is_collaborator)
	return is_collaborator, err
}

const listCollaborators = `-- name: ListCollaborators :many
SELECT id, trip_id, user_id, email, role, invite_token, invited_by, invited_at, accepted_at FROM trip_collaborators
WHERE trip_id = $1
ORDER BY invited_at
`

func (q *Queries) ListCollaborators(ctx context.Context, tripID uuid.UUID) ([]TripCollaborator, error) {
	rows, err := q.db.Query(ctx, listCollaborators, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripCollaborator{}
	for rows.Next() {
		var i TripCollaborator
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.InviteToken,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedTrips = `-- name: ListSharedTrips :many
SELECT t.id, t.user_id, t.title, t.description, t.status, t.start_date, t.end_date, t.created_at, t.updated_at, t.destination_country, t.completed_at, t.archive_after, t.archived_at, t.share_token, t.trial_started_at, t.trial_ends_at, t.destination_countries, t.expert_calls, t.search_vector, t.budget_cents, t.currency, t.notes FROM trips t
INNER JOIN trip_collaborators tc ON tc.trip_id = t.id
WHERE tc.user_id = $1 AND tc.accepted_at IS NOT NULL
ORDER BY t.created_at DESC
`

func (q *Queries) ListSharedTrips(ctx context.Context, userID pgtype.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listSharedTrips, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
			&i.CompletedAt,
			&i.ArchiveAfter,
			&i.ArchivedAt,
			&i.ShareToken,
			&i.TrialStartedAt,
			&i.TrialEndsAt,
			&i.DestinationCountries,
			&i.ExpertCalls,
			&i.SearchVector,
			&i.BudgetCents,
			&i.Currency,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollaborator = `-- name: RemoveCollaborator :exec
DELETE FROM trip_collaborators
WHERE trip_id = $1 AND email = $2
`

type RemoveCollaboratorParams struct {
	TripID uuid.UUID `json:"trip_id"`
	Email  string    `json:"email"`
}

func (q *Queries) RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error {
	_, err := q.db.Exec(ctx, removeCollaborator, arg.TripID, arg.Email)
	return err
}
