// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consents.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveConsents = `-- name: GetActiveConsents :many
SELECT id, user_id, consent_type, granted_at, withdrawn_at, ip_address, user_agent, created_at FROM user_consents
WHERE user_id = $1 AND withdrawn_at IS NULL
ORDER BY granted_at DESC
`

func (q *Queries) GetActiveConsents(ctx context.Context, userID uuid.UUID) ([]UserConsent, error) {
	rows, err := q.db.Query(ctx, getActiveConsents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserConsent{}
	for rows.Next() {
		var i UserConsent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConsentType,
			&i.GrantedAt,
			&i.WithdrawnAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasActiveConsent = `-- name: HasActiveConsent :one
SELECT EXISTS(
    SELECT 1 FROM user_consents
    WHERE user_id = $1 AND consent_type = $2 AND withdrawn_at IS NULL
) AS has_consent
`

type HasActiveConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) HasActiveConsent(ctx context.Context, arg HasActiveConsentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveConsent, arg.UserID, arg.ConsentType)
	var has_consent bool
	err := row.Scan(&has_consent)
	return has_consent, err
}

const recordConsent = `-- name: RecordConsent :one
INSERT INTO user_consents (user_id, consent_type, ip_address, user_agent)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, consent_type) WHERE withdrawn_at IS NULL
DO UPDATE SET granted_at = NOW(), ip_address = EXCLUDED.ip_address, user_agent = EXCLUDED.user_agent
RETURNING id, user_id, consent_type, granted_at, withdrawn_at, ip_address, user_agent, created_at
`

type RecordConsentParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ConsentType string      `json:"consent_type"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) RecordConsent(ctx context.Context, arg RecordConsentParams) (UserConsent, error) {
	row := q.db.QueryRow(ctx, recordConsent,
		arg.UserID,
		arg.ConsentType,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UserConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const withdrawConsent = `-- name: WithdrawConsent :exec
UPDATE user_consents
SET withdrawn_at = NOW()
WHERE user_id = $1 AND consent_type = $2 AND withdrawn_at IS NULL
`

type WithdrawConsentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error {
	_, err := q.db.Exec(ctx, withdrawConsent, arg.UserID, arg.ConsentType)
	return err
}
