// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedback = `-- name: CountFeedback :one
SELECT COUNT(*) FROM feedback
`

func (q *Queries) CountFeedback(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedback)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (user_id, type, message, context, page, trip_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, message, context, page, trip_id, created_at
`

type CreateFeedbackParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Type    string      `json:"type"`
	Message string      `json:"message"`
	Context []byte      `json:"context"`
	Page    pgtype.Text `json:"page"`
	TripID  pgtype.UUID `json:"trip_id"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.UserID,
		arg.Type,
		arg.Message,
		arg.Context,
		arg.Page,
		arg.TripID,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.Context,
		&i.Page,
		&i.TripID,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedback = `-- name: ListFeedback :many
SELECT f.id, f.user_id, f.type, f.message, f.context, f.page, f.trip_id, f.created_at, u.email, u.name
FROM feedback f
JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $1
`

type ListFeedbackParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListFeedbackRow struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Type      string      `json:"type"`
	Message   string      `json:"message"`
	Context   []byte      `json:"context"`
	Page      pgtype.Text `json:"page"`
	TripID    pgtype.UUID `json:"trip_id"`
	CreatedAt time.Time   `json:"created_at"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
}

func (q *Queries) ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]ListFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listFeedback, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackRow{}
	for rows.Next() {
		var i ListFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.Context,
			&i.Page,
			&i.TripID,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackByType = `-- name: ListFeedbackByType :many
SELECT f.id, f.user_id, f.type, f.message, f.context, f.page, f.trip_id, f.created_at, u.email, u.name
FROM feedback f
JOIN users u ON f.user_id = u.id
WHERE f.type = $1
ORDER BY f.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFeedbackByTypeParams struct {
	Type       string `json:"type"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

type ListFeedbackByTypeRow struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Type      string      `json:"type"`
	Message   string      `json:"message"`
	Context   []byte      `json:"context"`
	Page      pgtype.Text `json:"page"`
	TripID    pgtype.UUID `json:"trip_id"`
	CreatedAt time.Time   `json:"created_at"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
}

func (q *Queries) ListFeedbackByType(ctx context.Context, arg ListFeedbackByTypeParams) ([]ListFeedbackByTypeRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackByType, arg.Type, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackByTypeRow{}
	for rows.Next() {
		var i ListFeedbackByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.Context,
			&i.Page,
			&i.TripID,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
