// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: itinerary.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItineraryItem = `-- name: CreateItineraryItem :one
INSERT INTO itinerary_items (trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at
`

type CreateItineraryItemParams struct {
	TripID      uuid.UUID          `json:"trip_id"`
	DayNumber   pgtype.Int4        `json:"day_number"`
	OrderInDay  pgtype.Int4        `json:"order_in_day"`
	Type        pgtype.Text        `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Location    interface{}        `json:"location"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) CreateItineraryItem(ctx context.Context, arg CreateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItem,
		arg.TripID,
		arg.DayNumber,
		arg.OrderInDay,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Metadata,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItineraryItem = `-- name: DeleteItineraryItem :exec
DELETE FROM itinerary_items
WHERE itinerary_items.id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = itinerary_items.trip_id AND trips.user_id = $2)
`

type DeleteItineraryItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItineraryItem(ctx context.Context, arg DeleteItineraryItemParams) error {
	_, err := q.db.Exec(ctx, deleteItineraryItem, arg.ID, arg.UserID)
	return err
}

const deleteItineraryItemsByTrip = `-- name: DeleteItineraryItemsByTrip :exec
DELETE FROM itinerary_items
WHERE trip_id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = $1 AND trips.user_id = $2)
`

type DeleteItineraryItemsByTripParams struct {
	TripID uuid.UUID `json:"trip_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItineraryItemsByTrip(ctx context.Context, arg DeleteItineraryItemsByTripParams) error {
	_, err := q.db.Exec(ctx, deleteItineraryItemsByTrip, arg.TripID, arg.UserID)
	return err
}

const listItineraryItemsByTrip = `-- name: ListItineraryItemsByTrip :many
SELECT id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at FROM itinerary_items
WHERE trip_id = $1
ORDER BY day_number, order_in_day
`

func (q *Queries) ListItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, listItineraryItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryItem{}
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DayNumber,
			&i.OrderInDay,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItineraryItem = `-- name: UpdateItineraryItem :one
UPDATE itinerary_items
SET day_number = $2, order_in_day = $3, type = $4, title = $5, description = $6,
    location = $7, start_time = $8, end_time = $9, metadata = $10
WHERE itinerary_items.id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = itinerary_items.trip_id AND trips.user_id = $11)
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at
`

type UpdateItineraryItemParams struct {
	ID          uuid.UUID          `json:"id"`
	DayNumber   pgtype.Int4        `json:"day_number"`
	OrderInDay  pgtype.Int4        `json:"order_in_day"`
	Type        pgtype.Text        `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Location    interface{}        `json:"location"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Metadata    []byte             `json:"metadata"`
	UserID      uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateItineraryItem(ctx context.Context, arg UpdateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, updateItineraryItem,
		arg.ID,
		arg.DayNumber,
		arg.OrderInDay,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Metadata,
		arg.UserID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
