// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: itinerary.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cloneItineraryItems = `-- name: CloneItineraryItems :exec
INSERT INTO itinerary_items (trip_id, day_number, order_in_day, type, title, description, metadata, estimated_cost_cents, cost_currency)
SELECT $1::uuid, day_number, order_in_day, type, title, description, metadata, estimated_cost_cents, cost_currency
FROM itinerary_items
WHERE trip_id = $2::uuid
`

type CloneItineraryItemsParams struct {
	NewTripID    uuid.UUID `json:"new_trip_id"`
	SourceTripID uuid.UUID `json:"source_trip_id"`
}

func (q *Queries) CloneItineraryItems(ctx context.Context, arg CloneItineraryItemsParams) error {
	_, err := q.db.Exec(ctx, cloneItineraryItems, arg.NewTripID, arg.SourceTripID)
	return err
}

const createItineraryItem = `-- name: CreateItineraryItem :one
INSERT INTO itinerary_items (trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, estimated_cost_cents, cost_currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id
`

type CreateItineraryItemParams struct {
	TripID             uuid.UUID          `json:"trip_id"`
	DayNumber          pgtype.Int4        `json:"day_number"`
	OrderInDay         pgtype.Int4        `json:"order_in_day"`
	Type               pgtype.Text        `json:"type"`
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Location           interface{}        `json:"location"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	EndTime            pgtype.Timestamptz `json:"end_time"`
	Metadata           []byte             `json:"metadata"`
	EstimatedCostCents pgtype.Int8        `json:"estimated_cost_cents"`
	CostCurrency       pgtype.Text        `json:"cost_currency"`
}

func (q *Queries) CreateItineraryItem(ctx context.Context, arg CreateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItem,
		arg.TripID,
		arg.DayNumber,
		arg.OrderInDay,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Metadata,
		arg.EstimatedCostCents,
		arg.CostCurrency,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}

const createItineraryItemForOwnerOrEditor = `-- name: CreateItineraryItemForOwnerOrEditor :one
INSERT INTO itinerary_items (trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, estimated_cost_cents, cost_currency)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
FROM trips t
WHERE t.id = $1
  AND (
    t.user_id = $13
    OR EXISTS (
      SELECT 1 FROM trip_collaborators tc
      WHERE tc.trip_id = t.id
        AND tc.user_id = $13
        AND tc.accepted_at IS NOT NULL
        AND tc.role = 'editor'
    )
  )
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id
`

type CreateItineraryItemForOwnerOrEditorParams struct {
	TripID             uuid.UUID          `json:"trip_id"`
	DayNumber          pgtype.Int4        `json:"day_number"`
	OrderInDay         pgtype.Int4        `json:"order_in_day"`
	Type               pgtype.Text        `json:"type"`
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Location           interface{}        `json:"location"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	EndTime            pgtype.Timestamptz `json:"end_time"`
	Metadata           []byte             `json:"metadata"`
	EstimatedCostCents pgtype.Int8        `json:"estimated_cost_cents"`
	CostCurrency       pgtype.Text        `json:"cost_currency"`
	UserID             uuid.UUID          `json:"user_id"`
}

// Authz-gated insert used by ReplaceItineraryForOwnerOrEditor (#346):
// the WHERE clause re-checks ownership on every insert so a collaborator
// who is demoted mid-transaction (after the outer CanEditTrip pre-check
// but before the inserts land) cannot sneak new items into someone
// else's trip. When the predicate fails the INSERT matches zero rows
// and returns ErrNoRows; the service translates that to
// trip.ErrNotOwnerOrEditor and rolls back the entire transaction.
//
// Parameters: $1=trip_id $2=day_number $3=order_in_day $4=type
// $5=title $6=description $7=location $8=start_time $9=end_time
// $10=metadata $11=estimated_cost_cents $12=cost_currency $13=user_id
func (q *Queries) CreateItineraryItemForOwnerOrEditor(ctx context.Context, arg CreateItineraryItemForOwnerOrEditorParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItemForOwnerOrEditor,
		arg.TripID,
		arg.DayNumber,
		arg.OrderInDay,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Metadata,
		arg.EstimatedCostCents,
		arg.CostCurrency,
		arg.UserID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}

const createItineraryItemFromBooking = `-- name: CreateItineraryItemFromBooking :one
INSERT INTO itinerary_items (trip_id, day_number, order_in_day, type, title, description, start_time, end_time, booking_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id
`

type CreateItineraryItemFromBookingParams struct {
	TripID      uuid.UUID          `json:"trip_id"`
	DayNumber   pgtype.Int4        `json:"day_number"`
	OrderInDay  pgtype.Int4        `json:"order_in_day"`
	Type        pgtype.Text        `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	BookingID   pgtype.UUID        `json:"booking_id"`
}

func (q *Queries) CreateItineraryItemFromBooking(ctx context.Context, arg CreateItineraryItemFromBookingParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItemFromBooking,
		arg.TripID,
		arg.DayNumber,
		arg.OrderInDay,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.BookingID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}

const deleteItineraryItem = `-- name: DeleteItineraryItem :execrows
DELETE FROM itinerary_items
WHERE itinerary_items.id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = itinerary_items.trip_id AND trips.user_id = $2)
`

type DeleteItineraryItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItineraryItem(ctx context.Context, arg DeleteItineraryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItineraryItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItineraryItemByOwnerOrEditor = `-- name: DeleteItineraryItemByOwnerOrEditor :execrows
DELETE FROM itinerary_items ii
WHERE ii.id = $1
  AND ii.trip_id IN (
    SELECT t.id FROM trips t WHERE t.id = ii.trip_id AND (
      t.user_id = $2
      OR EXISTS (
        SELECT 1 FROM trip_collaborators tc
        WHERE tc.trip_id = t.id AND tc.user_id = $2 AND tc.accepted_at IS NOT NULL AND tc.role = 'editor'
      )
    )
  )
`

type DeleteItineraryItemByOwnerOrEditorParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItineraryItemByOwnerOrEditor(ctx context.Context, arg DeleteItineraryItemByOwnerOrEditorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItineraryItemByOwnerOrEditor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItineraryItemsByTrip = `-- name: DeleteItineraryItemsByTrip :execrows
DELETE FROM itinerary_items
WHERE trip_id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = $1 AND trips.user_id = $2)
`

type DeleteItineraryItemsByTripParams struct {
	TripID uuid.UUID `json:"trip_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItineraryItemsByTrip(ctx context.Context, arg DeleteItineraryItemsByTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItineraryItemsByTrip, arg.TripID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItineraryItemsByTripForOwnerOrEditor = `-- name: DeleteItineraryItemsByTripForOwnerOrEditor :execrows
DELETE FROM itinerary_items ii
WHERE ii.trip_id = $1
  AND ii.trip_id IN (
    SELECT t.id FROM trips t WHERE t.id = $1 AND (
      t.user_id = $2
      OR EXISTS (
        SELECT 1 FROM trip_collaborators tc
        WHERE tc.trip_id = t.id AND tc.user_id = $2 AND tc.accepted_at IS NOT NULL AND tc.role = 'editor'
      )
    )
  )
`

type DeleteItineraryItemsByTripForOwnerOrEditorParams struct {
	TripID uuid.UUID `json:"trip_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItineraryItemsByTripForOwnerOrEditor(ctx context.Context, arg DeleteItineraryItemsByTripForOwnerOrEditorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItineraryItemsByTripForOwnerOrEditor, arg.TripID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItineraryItemByBooking = `-- name: GetItineraryItemByBooking :one
SELECT id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id FROM itinerary_items
WHERE booking_id = $1 AND trip_id = $2
LIMIT 1
`

type GetItineraryItemByBookingParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	TripID    uuid.UUID   `json:"trip_id"`
}

func (q *Queries) GetItineraryItemByBooking(ctx context.Context, arg GetItineraryItemByBookingParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, getItineraryItemByBooking, arg.BookingID, arg.TripID)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}

const getItineraryItemByID = `-- name: GetItineraryItemByID :one
SELECT id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id FROM itinerary_items
WHERE itinerary_items.id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = itinerary_items.trip_id AND trips.user_id = $2)
`

type GetItineraryItemByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetItineraryItemByID(ctx context.Context, arg GetItineraryItemByIDParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, getItineraryItemByID, arg.ID, arg.UserID)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}

const listItineraryItemsByTrip = `-- name: ListItineraryItemsByTrip :many
SELECT id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id FROM itinerary_items
WHERE trip_id = $1
ORDER BY day_number, order_in_day, start_time, id
`

func (q *Queries) ListItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, listItineraryItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryItem{}
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DayNumber,
			&i.OrderInDay,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.Metadata,
			&i.CreatedAt,
			&i.EstimatedCostCents,
			&i.CostCurrency,
			&i.BookingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveItineraryItem = `-- name: MoveItineraryItem :one
UPDATE itinerary_items
SET day_number = $1, order_in_day = $2
WHERE itinerary_items.id = $3
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = itinerary_items.trip_id AND trips.user_id = $4)
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id
`

type MoveItineraryItemParams struct {
	DayNumber  pgtype.Int4 `json:"day_number"`
	OrderInDay pgtype.Int4 `json:"order_in_day"`
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
}

func (q *Queries) MoveItineraryItem(ctx context.Context, arg MoveItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, moveItineraryItem,
		arg.DayNumber,
		arg.OrderInDay,
		arg.ID,
		arg.UserID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}

const searchItineraryItems = `-- name: SearchItineraryItems :many
SELECT ii.id, ii.trip_id, ii.day_number, ii.order_in_day, ii.type, ii.title, ii.description, ii.location, ii.start_time, ii.end_time, ii.metadata, ii.created_at, ii.estimated_cost_cents, ii.cost_currency, ii.booking_id FROM itinerary_items ii
JOIN trips t ON t.id = ii.trip_id
WHERE t.user_id = $1
  AND (ii.title ILIKE '%' || $2 || '%' OR ii.description ILIKE '%' || $2 || '%')
ORDER BY ii.created_at DESC
LIMIT $3
`

type SearchItineraryItemsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Query      pgtype.Text `json:"query"`
	MaxResults int32       `json:"max_results"`
}

func (q *Queries) SearchItineraryItems(ctx context.Context, arg SearchItineraryItemsParams) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, searchItineraryItems, arg.UserID, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItineraryItem{}
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DayNumber,
			&i.OrderInDay,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.Metadata,
			&i.CreatedAt,
			&i.EstimatedCostCents,
			&i.CostCurrency,
			&i.BookingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItineraryItem = `-- name: UpdateItineraryItem :one
UPDATE itinerary_items
SET day_number = $2, order_in_day = $3, type = $4, title = $5, description = $6,
    location = $7, start_time = $8, end_time = $9, metadata = $10
WHERE itinerary_items.id = $1
  AND trip_id IN (SELECT trips.id FROM trips WHERE trips.id = itinerary_items.trip_id AND trips.user_id = $11)
RETURNING id, trip_id, day_number, order_in_day, type, title, description, location, start_time, end_time, metadata, created_at, estimated_cost_cents, cost_currency, booking_id
`

type UpdateItineraryItemParams struct {
	ID          uuid.UUID          `json:"id"`
	DayNumber   pgtype.Int4        `json:"day_number"`
	OrderInDay  pgtype.Int4        `json:"order_in_day"`
	Type        pgtype.Text        `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Location    interface{}        `json:"location"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Metadata    []byte             `json:"metadata"`
	UserID      uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateItineraryItem(ctx context.Context, arg UpdateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, updateItineraryItem,
		arg.ID,
		arg.DayNumber,
		arg.OrderInDay,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Metadata,
		arg.UserID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DayNumber,
		&i.OrderInDay,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Metadata,
		&i.CreatedAt,
		&i.EstimatedCostCents,
		&i.CostCurrency,
		&i.BookingID,
	)
	return i, err
}
