// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lifecycle.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTrip = `-- name: ArchiveTrip :exec
UPDATE trips
SET status = 'archived', archived_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type ArchiveTripParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveTrip(ctx context.Context, arg ArchiveTripParams) error {
	_, err := q.db.Exec(ctx, archiveTrip, arg.ID, arg.UserID)
	return err
}

const completeDeletionRequest = `-- name: CompleteDeletionRequest :exec
UPDATE deletion_requests
SET status = 'completed', completed_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteDeletionRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeDeletionRequest, id)
	return err
}

const completeExportRequest = `-- name: CompleteExportRequest :exec
UPDATE export_requests
SET status = 'completed', completed_at = NOW(), download_url = $2, expires_at = $3
WHERE id = $1
`

type CompleteExportRequestParams struct {
	ID          uuid.UUID          `json:"id"`
	DownloadUrl pgtype.Text        `json:"download_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CompleteExportRequest(ctx context.Context, arg CompleteExportRequestParams) error {
	_, err := q.db.Exec(ctx, completeExportRequest, arg.ID, arg.DownloadUrl, arg.ExpiresAt)
	return err
}

const completeTrip = `-- name: CompleteTrip :exec
UPDATE trips
SET status = 'completed',
    completed_at = NOW(),
    archive_after = NOW() + INTERVAL '90 days',
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type CompleteTripParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CompleteTrip(ctx context.Context, arg CompleteTripParams) error {
	_, err := q.db.Exec(ctx, completeTrip, arg.ID, arg.UserID)
	return err
}

const createDeletionRequest = `-- name: CreateDeletionRequest :one
INSERT INTO deletion_requests (user_id)
VALUES ($1)
RETURNING id, user_id, requested_at, completed_at, status, retry_count
`

func (q *Queries) CreateDeletionRequest(ctx context.Context, userID uuid.UUID) (DeletionRequest, error) {
	row := q.db.QueryRow(ctx, createDeletionRequest, userID)
	var i DeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.Status,
		&i.RetryCount,
	)
	return i, err
}

const createExportRequest = `-- name: CreateExportRequest :one
INSERT INTO export_requests (user_id)
VALUES ($1)
RETURNING id, user_id, requested_at, completed_at, download_url, expires_at, status
`

func (q *Queries) CreateExportRequest(ctx context.Context, userID uuid.UUID) (ExportRequest, error) {
	row := q.db.QueryRow(ctx, createExportRequest, userID)
	var i ExportRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.DownloadUrl,
		&i.ExpiresAt,
		&i.Status,
	)
	return i, err
}

const deleteTripByUser = `-- name: DeleteTripByUser :exec
DELETE FROM trips WHERE id = $1 AND user_id = $2
`

type DeleteTripByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTripByUser(ctx context.Context, arg DeleteTripByUserParams) error {
	_, err := q.db.Exec(ctx, deleteTripByUser, arg.ID, arg.UserID)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const failDeletionRequest = `-- name: FailDeletionRequest :exec
UPDATE deletion_requests
SET status = 'failed'
WHERE id = $1
`

func (q *Queries) FailDeletionRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failDeletionRequest, id)
	return err
}

const getAllTripIDsForUser = `-- name: GetAllTripIDsForUser :many
SELECT id FROM trips WHERE user_id = $1
`

func (q *Queries) GetAllTripIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllTripIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportRequestByID = `-- name: GetExportRequestByID :one
SELECT id, user_id, requested_at, completed_at, download_url, expires_at, status
FROM export_requests
WHERE id = $1
`

func (q *Queries) GetExportRequestByID(ctx context.Context, id uuid.UUID) (ExportRequest, error) {
	row := q.db.QueryRow(ctx, getExportRequestByID, id)
	var i ExportRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.DownloadUrl,
		&i.ExpiresAt,
		&i.Status,
	)
	return i, err
}

const getPendingDeletionRequests = `-- name: GetPendingDeletionRequests :many
SELECT id, user_id, requested_at
FROM deletion_requests
WHERE status = 'pending'
ORDER BY requested_at ASC
`

type GetPendingDeletionRequestsRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	RequestedAt time.Time `json:"requested_at"`
}

func (q *Queries) GetPendingDeletionRequests(ctx context.Context) ([]GetPendingDeletionRequestsRow, error) {
	rows, err := q.db.Query(ctx, getPendingDeletionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingDeletionRequestsRow{}
	for rows.Next() {
		var i GetPendingDeletionRequestsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.RequestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleDeletionRequests = `-- name: GetStaleDeletionRequests :many
SELECT id, user_id, requested_at, retry_count
FROM deletion_requests
WHERE status = 'processing'
  AND requested_at < NOW() - INTERVAL '1 hour'
ORDER BY requested_at ASC
`

type GetStaleDeletionRequestsRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	RequestedAt time.Time `json:"requested_at"`
	RetryCount  int32     `json:"retry_count"`
}

func (q *Queries) GetStaleDeletionRequests(ctx context.Context) ([]GetStaleDeletionRequestsRow, error) {
	rows, err := q.db.Query(ctx, getStaleDeletionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleDeletionRequestsRow{}
	for rows.Next() {
		var i GetStaleDeletionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripsToArchive = `-- name: GetTripsToArchive :many
SELECT id, user_id
FROM trips
WHERE status = 'completed'
  AND archive_after IS NOT NULL
  AND archive_after < NOW()
  AND archived_at IS NULL
`

type GetTripsToArchiveRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripsToArchive(ctx context.Context) ([]GetTripsToArchiveRow, error) {
	rows, err := q.db.Query(ctx, getTripsToArchive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripsToArchiveRow{}
	for rows.Next() {
		var i GetTripsToArchiveRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserExportRequests = `-- name: GetUserExportRequests :many
SELECT id, requested_at, completed_at, download_url, expires_at, status
FROM export_requests
WHERE user_id = $1
ORDER BY requested_at DESC
LIMIT 10
`

type GetUserExportRequestsRow struct {
	ID          uuid.UUID          `json:"id"`
	RequestedAt time.Time          `json:"requested_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	DownloadUrl pgtype.Text        `json:"download_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Status      string             `json:"status"`
}

func (q *Queries) GetUserExportRequests(ctx context.Context, userID uuid.UUID) ([]GetUserExportRequestsRow, error) {
	rows, err := q.db.Query(ctx, getUserExportRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserExportRequestsRow{}
	for rows.Next() {
		var i GetUserExportRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.DownloadUrl,
			&i.ExpiresAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDeletionRetryCount = `-- name: IncrementDeletionRetryCount :exec
UPDATE deletion_requests
SET retry_count = retry_count + 1, status = 'processing'
WHERE id = $1
`

func (q *Queries) IncrementDeletionRetryCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementDeletionRetryCount, id)
	return err
}

const setDeletionRequestProcessing = `-- name: SetDeletionRequestProcessing :exec
UPDATE deletion_requests
SET status = 'processing'
WHERE id = $1
`

func (q *Queries) SetDeletionRequestProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDeletionRequestProcessing, id)
	return err
}
