// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package dbgen

import (
	"context"
)

const countActiveUsersLast7Days = `-- name: CountActiveUsersLast7Days :one
SELECT COUNT(DISTINCT user_id) FROM daily_usage WHERE date >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) CountActiveUsersLast7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersLast7Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesToday = `-- name: CountMessagesToday :one
SELECT COALESCE(SUM(message_count), 0)::bigint FROM daily_usage WHERE date = CURRENT_DATE
`

func (q *Queries) CountMessagesToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesToday)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProUsers = `-- name: CountProUsers :one
SELECT COUNT(*) FROM users WHERE subscription_tier = 'pro'
`

func (q *Queries) CountProUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsLast7Days = `-- name: CountSignupsLast7Days :one
SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) CountSignupsLast7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsLast7Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsToday = `-- name: CountSignupsToday :one
SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE
`

func (q *Queries) CountSignupsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalTrips = `-- name: CountTotalTrips :one
SELECT COUNT(*) FROM trips
`

func (q *Queries) CountTotalTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalTrips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripProPurchases = `-- name: CountTripProPurchases :one
SELECT COUNT(*) FROM helcim_payments
`

func (q *Queries) CountTripProPurchases(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTripProPurchases)
	var count int64
	err := row.Scan(&count)
	return count, err
}
