// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID                uuid.UUID          `json:"id"`
	TripID            pgtype.UUID        `json:"trip_id"`
	UserID            uuid.UUID          `json:"user_id"`
	Type              string             `json:"type"`
	ConfirmationCode  pgtype.Text        `json:"confirmation_code"`
	Provider          pgtype.Text        `json:"provider"`
	Title             string             `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Location          interface{}        `json:"location"`
	Address           pgtype.Text        `json:"address"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         pgtype.Text        `json:"raw_source"`
	Source            string             `json:"source"`
	CreatedAt         time.Time          `json:"created_at"`
	DepartureLocation pgtype.Text        `json:"departure_location"`
	ArrivalLocation   pgtype.Text        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
}

type DailyUsage struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	Date         *time.Time `json:"date"`
	MessageCount int32      `json:"message_count"`
	AiCostCents  int32      `json:"ai_cost_cents"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type DeletionRequest struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RequestedAt time.Time          `json:"requested_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
}

type ExportRequest struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RequestedAt time.Time          `json:"requested_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	DownloadUrl pgtype.Text        `json:"download_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Status      string             `json:"status"`
}

type Feedback struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Type      string      `json:"type"`
	Message   string      `json:"message"`
	Context   []byte      `json:"context"`
	Page      pgtype.Text `json:"page"`
	TripID    pgtype.UUID `json:"trip_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type HelcimCheckoutSession struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	TripID        uuid.UUID          `json:"trip_id"`
	CheckoutToken string             `json:"checkout_token"`
	SecretToken   string             `json:"secret_token"`
	AmountCents   int32              `json:"amount_cents"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type HelcimPayment struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	TripID              uuid.UUID   `json:"trip_id"`
	HelcimTransactionID string      `json:"helcim_transaction_id"`
	ApprovalCode        pgtype.Text `json:"approval_code"`
	CardToken           pgtype.Text `json:"card_token"`
	AmountCents         int32       `json:"amount_cents"`
	Currency            string      `json:"currency"`
	Status              string      `json:"status"`
	ResponseHash        pgtype.Text `json:"response_hash"`
	CreatedAt           time.Time   `json:"created_at"`
}

type ItineraryItem struct {
	ID          uuid.UUID          `json:"id"`
	TripID      uuid.UUID          `json:"trip_id"`
	DayNumber   pgtype.Int4        `json:"day_number"`
	OrderInDay  pgtype.Int4        `json:"order_in_day"`
	Type        pgtype.Text        `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Location    interface{}        `json:"location"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   time.Time          `json:"created_at"`
}

type ProInterest struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type Referral struct {
	ID                    uuid.UUID          `json:"id"`
	ReferrerID            uuid.UUID          `json:"referrer_id"`
	RefereeID             pgtype.UUID        `json:"referee_id"`
	Code                  string             `json:"code"`
	RedeemedAt            pgtype.Timestamptz `json:"redeemed_at"`
	ReferrerRewardGranted bool               `json:"referrer_reward_granted"`
	RefereeRewardGranted  bool               `json:"referee_reward_granted"`
	CreatedAt             time.Time          `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Jti       string    `json:"jti"`
	Family    uuid.UUID `json:"family"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Subscription struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	Tier                 string             `json:"tier"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    pgtype.Bool        `json:"cancel_at_period_end"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Theme struct {
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Trip struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Status               string             `json:"status"`
	StartDate            pgtype.Date        `json:"start_date"`
	EndDate              pgtype.Date        `json:"end_date"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DestinationCountry   pgtype.Text        `json:"destination_country"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ArchiveAfter         pgtype.Timestamptz `json:"archive_after"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	ShareToken           pgtype.Text        `json:"share_token"`
	TrialStartedAt       pgtype.Timestamptz `json:"trial_started_at"`
	TrialEndsAt          pgtype.Timestamptz `json:"trial_ends_at"`
	DestinationCountries []string           `json:"destination_countries"`
	ExpertCalls          int32              `json:"expert_calls"`
}

type TripCollaborator struct {
	ID          uuid.UUID          `json:"id"`
	TripID      uuid.UUID          `json:"trip_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	InviteToken pgtype.Text        `json:"invite_token"`
	InvitedBy   uuid.UUID          `json:"invited_by"`
	InvitedAt   time.Time          `json:"invited_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
}

type TripTheme struct {
	TripID     uuid.UUID `json:"trip_id"`
	ThemeSlug  string    `json:"theme_slug"`
	Confidence float32   `json:"confidence"`
	Source     string    `json:"source"`
	CreatedAt  time.Time `json:"created_at"`
}

type TripUnlock struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TripID     uuid.UUID   `json:"trip_id"`
	PaymentID  pgtype.UUID `json:"payment_id"`
	Source     string      `json:"source"`
	UnlockedAt time.Time   `json:"unlocked_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	Name             pgtype.Text        `json:"name"`
	GoogleID         string             `json:"google_id"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DefaultPersonaID pgtype.Text        `json:"default_persona_id"`
	SubscriptionTier string             `json:"subscription_tier"`
	AgeVerifiedAt    pgtype.Timestamptz `json:"age_verified_at"`
	FacebookID       pgtype.Text        `json:"facebook_id"`
}

type Waitlist struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	InviteCode  pgtype.Text        `json:"invite_code"`
	SignedUpAt  time.Time          `json:"signed_up_at"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	VerifyToken pgtype.Text        `json:"verify_token"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
}
