// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID                uuid.UUID          `json:"id"`
	TripID            pgtype.UUID        `json:"trip_id"`
	UserID            uuid.UUID          `json:"user_id"`
	Type              string             `json:"type"`
	ConfirmationCode  pgtype.Text        `json:"confirmation_code"`
	Provider          pgtype.Text        `json:"provider"`
	Title             string             `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Location          interface{}        `json:"location"`
	Address           pgtype.Text        `json:"address"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         pgtype.Text        `json:"raw_source"`
	Source            string             `json:"source"`
	CreatedAt         time.Time          `json:"created_at"`
	DepartureLocation pgtype.Text        `json:"departure_location"`
	ArrivalLocation   pgtype.Text        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
}

type DailyUsage struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	Date         *time.Time `json:"date"`
	MessageCount int32      `json:"message_count"`
	AiCostCents  int32      `json:"ai_cost_cents"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type DeletionRequest struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RequestedAt time.Time          `json:"requested_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Status      string             `json:"status"`
}

type ExportRequest struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RequestedAt time.Time          `json:"requested_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	DownloadUrl pgtype.Text        `json:"download_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Status      string             `json:"status"`
}

type ItineraryItem struct {
	ID          uuid.UUID          `json:"id"`
	TripID      uuid.UUID          `json:"trip_id"`
	DayNumber   pgtype.Int4        `json:"day_number"`
	OrderInDay  pgtype.Int4        `json:"order_in_day"`
	Type        pgtype.Text        `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Location    interface{}        `json:"location"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   time.Time          `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Jti       string    `json:"jti"`
	Family    uuid.UUID `json:"family"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Theme struct {
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Trip struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Status             string             `json:"status"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DestinationCountry pgtype.Text        `json:"destination_country"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ArchiveAfter       pgtype.Timestamptz `json:"archive_after"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ShareToken         pgtype.Text        `json:"share_token"`
}

type TripTheme struct {
	TripID     uuid.UUID `json:"trip_id"`
	ThemeSlug  string    `json:"theme_slug"`
	Confidence float32   `json:"confidence"`
	Source     string    `json:"source"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID               uuid.UUID   `json:"id"`
	Email            string      `json:"email"`
	Name             pgtype.Text `json:"name"`
	GoogleID         string      `json:"google_id"`
	AvatarUrl        pgtype.Text `json:"avatar_url"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	DefaultPersonaID pgtype.Text `json:"default_persona_id"`
	SubscriptionTier string      `json:"subscription_tier"`
}

type Waitlist struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	InviteCode pgtype.Text        `json:"invite_code"`
	SignedUpAt time.Time          `json:"signed_up_at"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
}
