// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserPayments = `-- name: CountUserPayments :one
SELECT COUNT(*) FROM helcim_payments WHERE user_id = $1
`

func (q *Queries) CountUserPayments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPayments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO helcim_checkout_sessions (user_id, trip_id, checkout_token, secret_token, amount_cents, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, trip_id, checkout_token, secret_token, amount_cents, currency, status, created_at, completed_at
`

type CreateCheckoutSessionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	TripID        uuid.UUID `json:"trip_id"`
	CheckoutToken string    `json:"checkout_token"`
	SecretToken   string    `json:"secret_token"`
	AmountCents   int32     `json:"amount_cents"`
	Currency      string    `json:"currency"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (HelcimCheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.UserID,
		arg.TripID,
		arg.CheckoutToken,
		arg.SecretToken,
		arg.AmountCents,
		arg.Currency,
	)
	var i HelcimCheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.CheckoutToken,
		&i.SecretToken,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO helcim_payments (user_id, trip_id, helcim_transaction_id, approval_code, card_token, amount_cents, currency, status, response_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, trip_id, helcim_transaction_id, approval_code, card_token, amount_cents, currency, status, response_hash, created_at
`

type CreatePaymentParams struct {
	UserID              uuid.UUID   `json:"user_id"`
	TripID              uuid.UUID   `json:"trip_id"`
	HelcimTransactionID string      `json:"helcim_transaction_id"`
	ApprovalCode        pgtype.Text `json:"approval_code"`
	CardToken           pgtype.Text `json:"card_token"`
	AmountCents         int32       `json:"amount_cents"`
	Currency            string      `json:"currency"`
	Status              string      `json:"status"`
	ResponseHash        pgtype.Text `json:"response_hash"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (HelcimPayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.TripID,
		arg.HelcimTransactionID,
		arg.ApprovalCode,
		arg.CardToken,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.ResponseHash,
	)
	var i HelcimPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.HelcimTransactionID,
		&i.ApprovalCode,
		&i.CardToken,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.ResponseHash,
		&i.CreatedAt,
	)
	return i, err
}

const createTripUnlock = `-- name: CreateTripUnlock :one
INSERT INTO trip_unlocks (user_id, trip_id, payment_id, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, trip_id) DO UPDATE SET payment_id = EXCLUDED.payment_id, unlocked_at = NOW()
RETURNING id, user_id, trip_id, payment_id, source, unlocked_at
`

type CreateTripUnlockParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TripID    uuid.UUID   `json:"trip_id"`
	PaymentID pgtype.UUID `json:"payment_id"`
	Source    string      `json:"source"`
}

func (q *Queries) CreateTripUnlock(ctx context.Context, arg CreateTripUnlockParams) (TripUnlock, error) {
	row := q.db.QueryRow(ctx, createTripUnlock,
		arg.UserID,
		arg.TripID,
		arg.PaymentID,
		arg.Source,
	)
	var i TripUnlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.PaymentID,
		&i.Source,
		&i.UnlockedAt,
	)
	return i, err
}

const getCheckoutSessionByToken = `-- name: GetCheckoutSessionByToken :one
SELECT id, user_id, trip_id, checkout_token, secret_token, amount_cents, currency, status, created_at, completed_at FROM helcim_checkout_sessions WHERE checkout_token = $1
`

func (q *Queries) GetCheckoutSessionByToken(ctx context.Context, checkoutToken string) (HelcimCheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionByToken, checkoutToken)
	var i HelcimCheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.CheckoutToken,
		&i.SecretToken,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPaymentByTransactionID = `-- name: GetPaymentByTransactionID :one
SELECT id, user_id, trip_id, helcim_transaction_id, approval_code, card_token, amount_cents, currency, status, response_hash, created_at FROM helcim_payments WHERE helcim_transaction_id = $1
`

func (q *Queries) GetPaymentByTransactionID(ctx context.Context, helcimTransactionID string) (HelcimPayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransactionID, helcimTransactionID)
	var i HelcimPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.HelcimTransactionID,
		&i.ApprovalCode,
		&i.CardToken,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.ResponseHash,
		&i.CreatedAt,
	)
	return i, err
}

const isTripUnlocked = `-- name: IsTripUnlocked :one
SELECT EXISTS(SELECT 1 FROM trip_unlocks WHERE user_id = $1 AND trip_id = $2)
`

type IsTripUnlockedParams struct {
	UserID uuid.UUID `json:"user_id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) IsTripUnlocked(ctx context.Context, arg IsTripUnlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTripUnlocked, arg.UserID, arg.TripID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT p.id, p.user_id, p.trip_id, p.helcim_transaction_id, p.approval_code, p.card_token, p.amount_cents, p.currency, p.status, p.response_hash, p.created_at, t.title as trip_title
FROM helcim_payments p
JOIN trips t ON t.id = p.trip_id
WHERE p.user_id = $1
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListUserPaymentsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageSize   int32     `json:"page_size"`
}

type ListUserPaymentsRow struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	TripID              uuid.UUID   `json:"trip_id"`
	HelcimTransactionID string      `json:"helcim_transaction_id"`
	ApprovalCode        pgtype.Text `json:"approval_code"`
	CardToken           pgtype.Text `json:"card_token"`
	AmountCents         int32       `json:"amount_cents"`
	Currency            string      `json:"currency"`
	Status              string      `json:"status"`
	ResponseHash        pgtype.Text `json:"response_hash"`
	CreatedAt           time.Time   `json:"created_at"`
	TripTitle           string      `json:"trip_title"`
}

func (q *Queries) ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]ListUserPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listUserPayments, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPaymentsRow{}
	for rows.Next() {
		var i ListUserPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TripID,
			&i.HelcimTransactionID,
			&i.ApprovalCode,
			&i.CardToken,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.ResponseHash,
			&i.CreatedAt,
			&i.TripTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTripUnlocks = `-- name: ListUserTripUnlocks :many
SELECT u.id, u.user_id, u.trip_id, u.payment_id, u.source, u.unlocked_at, t.title as trip_title
FROM trip_unlocks u
JOIN trips t ON t.id = u.trip_id
WHERE u.user_id = $1
ORDER BY u.unlocked_at DESC
`

type ListUserTripUnlocksRow struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TripID     uuid.UUID   `json:"trip_id"`
	PaymentID  pgtype.UUID `json:"payment_id"`
	Source     string      `json:"source"`
	UnlockedAt time.Time   `json:"unlocked_at"`
	TripTitle  string      `json:"trip_title"`
}

func (q *Queries) ListUserTripUnlocks(ctx context.Context, userID uuid.UUID) ([]ListUserTripUnlocksRow, error) {
	rows, err := q.db.Query(ctx, listUserTripUnlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTripUnlocksRow{}
	for rows.Next() {
		var i ListUserTripUnlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TripID,
			&i.PaymentID,
			&i.Source,
			&i.UnlockedAt,
			&i.TripTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckoutSessionComplete = `-- name: MarkCheckoutSessionComplete :exec
UPDATE helcim_checkout_sessions SET status = 'complete', completed_at = NOW()
WHERE checkout_token = $1 AND status = 'open'
`

func (q *Queries) MarkCheckoutSessionComplete(ctx context.Context, checkoutToken string) error {
	_, err := q.db.Exec(ctx, markCheckoutSessionComplete, checkoutToken)
	return err
}

const markCheckoutSessionExpired = `-- name: MarkCheckoutSessionExpired :exec
UPDATE helcim_checkout_sessions SET status = 'expired'
WHERE checkout_token = $1 AND status = 'open'
`

func (q *Queries) MarkCheckoutSessionExpired(ctx context.Context, checkoutToken string) error {
	_, err := q.db.Exec(ctx, markCheckoutSessionExpired, checkoutToken)
	return err
}
