// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserPayments = `-- name: CountUserPayments :one
SELECT COUNT(*) FROM payments WHERE user_id = $1
`

func (q *Queries) CountUserPayments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPayments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO checkout_sessions (user_id, trip_id, checkout_token, amount_cents, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, trip_id, checkout_token, amount_cents, currency, status, created_at, completed_at
`

type CreateCheckoutSessionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	TripID        uuid.UUID `json:"trip_id"`
	CheckoutToken string    `json:"checkout_token"`
	AmountCents   int32     `json:"amount_cents"`
	Currency      string    `json:"currency"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.UserID,
		arg.TripID,
		arg.CheckoutToken,
		arg.AmountCents,
		arg.Currency,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.CheckoutToken,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, trip_id, external_payment_id, amount_cents, currency, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, trip_id, external_payment_id, amount_cents, currency, status, created_at
`

type CreatePaymentParams struct {
	UserID            uuid.UUID `json:"user_id"`
	TripID            uuid.UUID `json:"trip_id"`
	ExternalPaymentID string    `json:"external_payment_id"`
	AmountCents       int32     `json:"amount_cents"`
	Currency          string    `json:"currency"`
	Status            string    `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.TripID,
		arg.ExternalPaymentID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.ExternalPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTripUnlock = `-- name: CreateTripUnlock :one
INSERT INTO trip_unlocks (user_id, trip_id, payment_id, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, trip_id) DO UPDATE SET payment_id = EXCLUDED.payment_id, unlocked_at = NOW()
RETURNING id, user_id, trip_id, payment_id, source, unlocked_at
`

type CreateTripUnlockParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TripID    uuid.UUID   `json:"trip_id"`
	PaymentID pgtype.UUID `json:"payment_id"`
	Source    string      `json:"source"`
}

func (q *Queries) CreateTripUnlock(ctx context.Context, arg CreateTripUnlockParams) (TripUnlock, error) {
	row := q.db.QueryRow(ctx, createTripUnlock,
		arg.UserID,
		arg.TripID,
		arg.PaymentID,
		arg.Source,
	)
	var i TripUnlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.PaymentID,
		&i.Source,
		&i.UnlockedAt,
	)
	return i, err
}

const getCheckoutSessionByToken = `-- name: GetCheckoutSessionByToken :one
SELECT id, user_id, trip_id, checkout_token, amount_cents, currency, status, created_at, completed_at FROM checkout_sessions WHERE checkout_token = $1
`

func (q *Queries) GetCheckoutSessionByToken(ctx context.Context, checkoutToken string) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionByToken, checkoutToken)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.CheckoutToken,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPaymentByTransactionID = `-- name: GetPaymentByTransactionID :one
SELECT id, user_id, trip_id, external_payment_id, amount_cents, currency, status, created_at FROM payments WHERE external_payment_id = $1
`

func (q *Queries) GetPaymentByTransactionID(ctx context.Context, externalPaymentID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransactionID, externalPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.ExternalPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const isTripUnlocked = `-- name: IsTripUnlocked :one
SELECT EXISTS(SELECT 1 FROM trip_unlocks WHERE user_id = $1 AND trip_id = $2)
`

type IsTripUnlockedParams struct {
	UserID uuid.UUID `json:"user_id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) IsTripUnlocked(ctx context.Context, arg IsTripUnlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTripUnlocked, arg.UserID, arg.TripID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT p.id, p.user_id, p.trip_id, p.external_payment_id, p.amount_cents, p.currency, p.status, p.created_at, t.title as trip_title
FROM payments p
JOIN trips t ON t.id = p.trip_id
WHERE p.user_id = $1
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListUserPaymentsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageSize   int32     `json:"page_size"`
}

type ListUserPaymentsRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	TripID            uuid.UUID `json:"trip_id"`
	ExternalPaymentID string    `json:"external_payment_id"`
	AmountCents       int32     `json:"amount_cents"`
	Currency          string    `json:"currency"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	TripTitle         string    `json:"trip_title"`
}

func (q *Queries) ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]ListUserPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listUserPayments, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPaymentsRow{}
	for rows.Next() {
		var i ListUserPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TripID,
			&i.ExternalPaymentID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.TripTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTripUnlocks = `-- name: ListUserTripUnlocks :many
SELECT u.id, u.user_id, u.trip_id, u.payment_id, u.source, u.unlocked_at, t.title as trip_title
FROM trip_unlocks u
JOIN trips t ON t.id = u.trip_id
WHERE u.user_id = $1
ORDER BY u.unlocked_at DESC
`

type ListUserTripUnlocksRow struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TripID     uuid.UUID   `json:"trip_id"`
	PaymentID  pgtype.UUID `json:"payment_id"`
	Source     string      `json:"source"`
	UnlockedAt time.Time   `json:"unlocked_at"`
	TripTitle  string      `json:"trip_title"`
}

func (q *Queries) ListUserTripUnlocks(ctx context.Context, userID uuid.UUID) ([]ListUserTripUnlocksRow, error) {
	rows, err := q.db.Query(ctx, listUserTripUnlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTripUnlocksRow{}
	for rows.Next() {
		var i ListUserTripUnlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TripID,
			&i.PaymentID,
			&i.Source,
			&i.UnlockedAt,
			&i.TripTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckoutSessionComplete = `-- name: MarkCheckoutSessionComplete :exec
UPDATE checkout_sessions SET status = 'complete', completed_at = NOW()
WHERE checkout_token = $1 AND status = 'open'
`

func (q *Queries) MarkCheckoutSessionComplete(ctx context.Context, checkoutToken string) error {
	_, err := q.db.Exec(ctx, markCheckoutSessionComplete, checkoutToken)
	return err
}

const markCheckoutSessionExpired = `-- name: MarkCheckoutSessionExpired :exec
UPDATE checkout_sessions SET status = 'expired'
WHERE checkout_token = $1 AND status = 'open'
`

func (q *Queries) MarkCheckoutSessionExpired(ctx context.Context, checkoutToken string) error {
	_, err := q.db.Exec(ctx, markCheckoutSessionExpired, checkoutToken)
	return err
}

const markStripeEventFailed = `-- name: MarkStripeEventFailed :exec
UPDATE stripe_events SET last_error = $1
WHERE id = $2
`

type MarkStripeEventFailedParams struct {
	LastError pgtype.Text `json:"last_error"`
	ID        string      `json:"id"`
}

func (q *Queries) MarkStripeEventFailed(ctx context.Context, arg MarkStripeEventFailedParams) error {
	_, err := q.db.Exec(ctx, markStripeEventFailed, arg.LastError, arg.ID)
	return err
}

const markStripeEventProcessed = `-- name: MarkStripeEventProcessed :exec
UPDATE stripe_events SET processed_at = NOW(), last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkStripeEventProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markStripeEventProcessed, id)
	return err
}

const recordStripeEvent = `-- name: RecordStripeEvent :one
INSERT INTO stripe_events (id, event_type)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET retry_count = stripe_events.retry_count + 1
RETURNING id, event_type, received_at, processed_at, retry_count, last_error
`

type RecordStripeEventParams struct {
	ID        string `json:"id"`
	EventType string `json:"event_type"`
}

// Idempotency record for Stripe webhook events. Returns the row's
// processed_at to let the handler decide whether to short-circuit.
// ON CONFLICT bumps retry_count so we can tell repeat retries apart from
// first-time deliveries; if processed_at IS NOT NULL on conflict, the
// handler returns 200 immediately without re-running side effects.
func (q *Queries) RecordStripeEvent(ctx context.Context, arg RecordStripeEventParams) (StripeEvent, error) {
	row := q.db.QueryRow(ctx, recordStripeEvent, arg.ID, arg.EventType)
	var i StripeEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RetryCount,
		&i.LastError,
	)
	return i, err
}
