// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deletePreference = `-- name: DeletePreference :exec
DELETE FROM user_preferences
WHERE user_id = $1 AND key = $2
`

type DeletePreferenceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

func (q *Queries) DeletePreference(ctx context.Context, arg DeletePreferenceParams) error {
	_, err := q.db.Exec(ctx, deletePreference, arg.UserID, arg.Key)
	return err
}

const getPreferences = `-- name: GetPreferences :many
SELECT id, user_id, key, value, updated_at FROM user_preferences
WHERE user_id = $1
ORDER BY key
`

func (q *Queries) GetPreferences(ctx context.Context, userID uuid.UUID) ([]UserPreference, error) {
	rows, err := q.db.Query(ctx, getPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPreference{}
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPreference = `-- name: UpsertPreference :one
INSERT INTO user_preferences (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE
    SET value = EXCLUDED.value,
        updated_at = NOW()
RETURNING id, user_id, key, value, updated_at
`

type UpsertPreferenceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
	Value  string    `json:"value"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreference, arg.UserID, arg.Key, arg.Value)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}
