// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pro_interest.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countProInterest = `-- name: CountProInterest :one
SELECT COUNT(*) FROM pro_interest
`

func (q *Queries) CountProInterest(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProInterest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProInterest = `-- name: ListProInterest :many
SELECT id, user_id, email, created_at FROM pro_interest ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListProInterestParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListProInterest(ctx context.Context, arg ListProInterestParams) ([]ProInterest, error) {
	rows, err := q.db.Query(ctx, listProInterest, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProInterest{}
	for rows.Next() {
		var i ProInterest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProInterest = `-- name: RecordProInterest :one
INSERT INTO pro_interest (user_id, email)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
RETURNING id, user_id, email, created_at
`

type RecordProInterestParams struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

func (q *Queries) RecordProInterest(ctx context.Context, arg RecordProInterestParams) (ProInterest, error) {
	row := q.db.QueryRow(ctx, recordProInterest, arg.UserID, arg.Email)
	var i ProInterest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
