// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referrals.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRewardsEarned = `-- name: CountRewardsEarned :one
SELECT COUNT(*) FROM referrals WHERE referrer_id = $1 AND referrer_reward_granted = true
`

func (q *Queries) CountRewardsEarned(ctx context.Context, referrerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRewardsEarned, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuccessfulReferrals = `-- name: CountSuccessfulReferrals :one
SELECT COUNT(*) FROM referrals WHERE referrer_id = $1 AND referee_id IS NOT NULL
`

func (q *Queries) CountSuccessfulReferrals(ctx context.Context, referrerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulReferrals, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (referrer_id, code) VALUES ($1, $2)
RETURNING id, referrer_id, referee_id, code, redeemed_at, referrer_reward_granted, referee_reward_granted, created_at
`

type CreateReferralParams struct {
	ReferrerID uuid.UUID `json:"referrer_id"`
	Code       string    `json:"code"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral, arg.ReferrerID, arg.Code)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.Code,
		&i.RedeemedAt,
		&i.ReferrerRewardGranted,
		&i.RefereeRewardGranted,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByCode = `-- name: GetReferralByCode :one
SELECT id, referrer_id, referee_id, code, redeemed_at, referrer_reward_granted, referee_reward_granted, created_at FROM referrals WHERE code = $1
`

func (q *Queries) GetReferralByCode(ctx context.Context, code string) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByCode, code)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.Code,
		&i.RedeemedAt,
		&i.ReferrerRewardGranted,
		&i.RefereeRewardGranted,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByReferee = `-- name: GetReferralByReferee :one
SELECT id, referrer_id, referee_id, code, redeemed_at, referrer_reward_granted, referee_reward_granted, created_at FROM referrals WHERE referee_id = $1 LIMIT 1
`

func (q *Queries) GetReferralByReferee(ctx context.Context, refereeID pgtype.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByReferee, refereeID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.Code,
		&i.RedeemedAt,
		&i.ReferrerRewardGranted,
		&i.RefereeRewardGranted,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByReferrer = `-- name: GetReferralByReferrer :one
SELECT id, referrer_id, referee_id, code, redeemed_at, referrer_reward_granted, referee_reward_granted, created_at FROM referrals WHERE referrer_id = $1 AND referee_id IS NULL
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetReferralByReferrer(ctx context.Context, referrerID uuid.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByReferrer, referrerID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.Code,
		&i.RedeemedAt,
		&i.ReferrerRewardGranted,
		&i.RefereeRewardGranted,
		&i.CreatedAt,
	)
	return i, err
}

const grantRefereeReward = `-- name: GrantRefereeReward :exec
UPDATE referrals SET referee_reward_granted = true WHERE id = $1
`

func (q *Queries) GrantRefereeReward(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, grantRefereeReward, id)
	return err
}

const grantReferralTripUnlock = `-- name: GrantReferralTripUnlock :one
INSERT INTO trip_unlocks (user_id, trip_id, source)
SELECT $1, t.id, 'referral'
FROM trips t
WHERE t.user_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM trip_unlocks tu WHERE tu.user_id = $1 AND tu.trip_id = t.id
  )
ORDER BY t.created_at DESC
LIMIT 1
ON CONFLICT (user_id, trip_id) DO NOTHING
RETURNING id, user_id, trip_id, payment_id, source, unlocked_at
`

func (q *Queries) GrantReferralTripUnlock(ctx context.Context, userID uuid.UUID) (TripUnlock, error) {
	row := q.db.QueryRow(ctx, grantReferralTripUnlock, userID)
	var i TripUnlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.PaymentID,
		&i.Source,
		&i.UnlockedAt,
	)
	return i, err
}

const grantReferrerReward = `-- name: GrantReferrerReward :exec
UPDATE referrals SET referrer_reward_granted = true WHERE id = $1
`

func (q *Queries) GrantReferrerReward(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, grantReferrerReward, id)
	return err
}

const hasPendingReferralCredit = `-- name: HasPendingReferralCredit :one
SELECT EXISTS(
  SELECT 1 FROM referrals r
  WHERE (r.referrer_id = $1 AND r.referrer_reward_granted = true)
) AND NOT EXISTS(
  SELECT 1 FROM trip_unlocks tu WHERE tu.user_id = $1 AND tu.source = 'referral'
)
`

func (q *Queries) HasPendingReferralCredit(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingReferralCredit, userID)
	var result bool
	err := row.Scan(&result)
	return result, err
}

const listReferralsByUser = `-- name: ListReferralsByUser :many
SELECT id, referrer_id, referee_id, code, redeemed_at, referrer_reward_granted, referee_reward_granted, created_at FROM referrals WHERE referrer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReferralsByUser(ctx context.Context, referrerID uuid.UUID) ([]Referral, error) {
	rows, err := q.db.Query(ctx, listReferralsByUser, referrerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Referral{}
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.RefereeID,
			&i.Code,
			&i.RedeemedAt,
			&i.ReferrerRewardGranted,
			&i.RefereeRewardGranted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemReferral = `-- name: RedeemReferral :exec
UPDATE referrals SET referee_id = $1, redeemed_at = NOW()
WHERE code = $2 AND referee_id IS NULL
`

type RedeemReferralParams struct {
	RefereeID pgtype.UUID `json:"referee_id"`
	Code      string      `json:"code"`
}

func (q *Queries) RedeemReferral(ctx context.Context, arg RedeemReferralParams) error {
	_, err := q.db.Exec(ctx, redeemReferral, arg.RefereeID, arg.Code)
	return err
}
