// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, stripe_customer_id, stripe_subscription_id, tier, status, current_period_start, current_period_end, billing_period)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    tier = EXCLUDED.tier,
    status = EXCLUDED.status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    billing_period = EXCLUDED.billing_period,
    updated_at = NOW()
RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, tier, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at, billing_period
`

type CreateSubscriptionParams struct {
	UserID               uuid.UUID          `json:"user_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	Tier                 string             `json:"tier"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	BillingPeriod        string             `json:"billing_period"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Tier,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.BillingPeriod,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingPeriod,
	)
	return i, err
}

const deleteSubscriptionByUserID = `-- name: DeleteSubscriptionByUserID :exec
DELETE FROM subscriptions WHERE user_id = $1
`

func (q *Queries) DeleteSubscriptionByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionByUserID, userID)
	return err
}

const getSubscriptionByStripeCustomer = `-- name: GetSubscriptionByStripeCustomer :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, tier, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at, billing_period FROM subscriptions WHERE stripe_customer_id = $1
`

func (q *Queries) GetSubscriptionByStripeCustomer(ctx context.Context, stripeCustomerID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingPeriod,
	)
	return i, err
}

const getSubscriptionByStripeSubscriptionID = `-- name: GetSubscriptionByStripeSubscriptionID :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, tier, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at, billing_period FROM subscriptions WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeSubscriptionID(ctx context.Context, stripeSubscriptionID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeSubscriptionID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingPeriod,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, tier, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at, billing_period FROM subscriptions WHERE user_id = $1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Tier,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingPeriod,
	)
	return i, err
}

const setSubscriptionCancelAtPeriodEnd = `-- name: SetSubscriptionCancelAtPeriodEnd :exec
UPDATE subscriptions SET cancel_at_period_end = $1, updated_at = NOW()
WHERE stripe_subscription_id = $2
`

type SetSubscriptionCancelAtPeriodEndParams struct {
	CancelAtPeriodEnd    pgtype.Bool `json:"cancel_at_period_end"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
}

func (q *Queries) SetSubscriptionCancelAtPeriodEnd(ctx context.Context, arg SetSubscriptionCancelAtPeriodEndParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionCancelAtPeriodEnd, arg.CancelAtPeriodEnd, arg.StripeSubscriptionID)
	return err
}

const updateSubscriptionBillingPeriod = `-- name: UpdateSubscriptionBillingPeriod :exec
UPDATE subscriptions SET billing_period = $1, updated_at = NOW()
WHERE stripe_subscription_id = $2
`

type UpdateSubscriptionBillingPeriodParams struct {
	BillingPeriod        string      `json:"billing_period"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionBillingPeriod(ctx context.Context, arg UpdateSubscriptionBillingPeriodParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionBillingPeriod, arg.BillingPeriod, arg.StripeSubscriptionID)
	return err
}

const updateSubscriptionPeriod = `-- name: UpdateSubscriptionPeriod :exec
UPDATE subscriptions SET
    current_period_start = $1,
    current_period_end = $2,
    updated_at = NOW()
WHERE stripe_subscription_id = $3
`

type UpdateSubscriptionPeriodParams struct {
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionPeriod(ctx context.Context, arg UpdateSubscriptionPeriodParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionPeriod, arg.CurrentPeriodStart, arg.CurrentPeriodEnd, arg.StripeSubscriptionID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions SET status = $1, updated_at = NOW()
WHERE stripe_subscription_id = $2
`

type UpdateSubscriptionStatusParams struct {
	Status               string      `json:"status"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.Status, arg.StripeSubscriptionID)
	return err
}

const updateSubscriptionTier = `-- name: UpdateSubscriptionTier :exec
UPDATE subscriptions SET tier = $1, updated_at = NOW()
WHERE stripe_subscription_id = $2
`

type UpdateSubscriptionTierParams struct {
	Tier                 string      `json:"tier"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionTier(ctx context.Context, arg UpdateSubscriptionTierParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionTier, arg.Tier, arg.StripeSubscriptionID)
	return err
}
