// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: themes.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearTripThemes = `-- name: ClearTripThemes :exec
DELETE FROM trip_themes
WHERE trip_id = $1 AND source = 'ai'
`

func (q *Queries) ClearTripThemes(ctx context.Context, tripID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTripThemes, tripID)
	return err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (slug, display_name, description, icon)
VALUES ($1, $2, $3, $4)
RETURNING slug, display_name, description, icon, created_at
`

type CreateThemeParams struct {
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.Icon,
	)
	var i Theme
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getTheme = `-- name: GetTheme :one
SELECT slug, display_name, description, icon, created_at
FROM themes
WHERE slug = $1
`

func (q *Queries) GetTheme(ctx context.Context, slug string) (Theme, error) {
	row := q.db.QueryRow(ctx, getTheme, slug)
	var i Theme
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getTripThemes = `-- name: GetTripThemes :many
SELECT t.slug, t.display_name, t.description, t.icon, tt.confidence, tt.source
FROM trip_themes tt
JOIN themes t ON t.slug = tt.theme_slug
WHERE tt.trip_id = $1
ORDER BY tt.confidence DESC
`

type GetTripThemesRow struct {
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Confidence  float32     `json:"confidence"`
	Source      string      `json:"source"`
}

func (q *Queries) GetTripThemes(ctx context.Context, tripID uuid.UUID) ([]GetTripThemesRow, error) {
	rows, err := q.db.Query(ctx, getTripThemes, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripThemesRow{}
	for rows.Next() {
		var i GetTripThemesRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Icon,
			&i.Confidence,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT slug, display_name, description, icon, created_at
FROM themes
ORDER BY display_name
`

func (q *Queries) ListThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTripTheme = `-- name: RemoveTripTheme :exec
DELETE FROM trip_themes
WHERE trip_id = $1 AND theme_slug = $2
`

type RemoveTripThemeParams struct {
	TripID    uuid.UUID `json:"trip_id"`
	ThemeSlug string    `json:"theme_slug"`
}

func (q *Queries) RemoveTripTheme(ctx context.Context, arg RemoveTripThemeParams) error {
	_, err := q.db.Exec(ctx, removeTripTheme, arg.TripID, arg.ThemeSlug)
	return err
}

const setTripTheme = `-- name: SetTripTheme :exec
INSERT INTO trip_themes (trip_id, theme_slug, confidence, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (trip_id, theme_slug) DO UPDATE
SET confidence = EXCLUDED.confidence, source = EXCLUDED.source
`

type SetTripThemeParams struct {
	TripID     uuid.UUID `json:"trip_id"`
	ThemeSlug  string    `json:"theme_slug"`
	Confidence float32   `json:"confidence"`
	Source     string    `json:"source"`
}

func (q *Queries) SetTripTheme(ctx context.Context, arg SetTripThemeParams) error {
	_, err := q.db.Exec(ctx, setTripTheme,
		arg.TripID,
		arg.ThemeSlug,
		arg.Confidence,
		arg.Source,
	)
	return err
}
