// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTripsByUser = `-- name: CountTripsByUser :one
SELECT COUNT(*) FROM trips WHERE user_id = $1
`

func (q *Queries) CountTripsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripsByUserAndStatus = `-- name: CountTripsByUserAndStatus :one
SELECT COUNT(*) FROM trips WHERE user_id = $1 AND status = $2
`

type CountTripsByUserAndStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) CountTripsByUserAndStatus(ctx context.Context, arg CountTripsByUserAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsByUserAndStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (user_id, title, description, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token
`

type CreateTripParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = $1 AND user_id = $2
`

type DeleteTripParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTrip(ctx context.Context, arg DeleteTripParams) error {
	_, err := q.db.Exec(ctx, deleteTrip, arg.ID, arg.UserID)
	return err
}

const disableTripSharing = `-- name: DisableTripSharing :one
UPDATE trips SET share_token = NULL, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token
`

type DisableTripSharingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DisableTripSharing(ctx context.Context, arg DisableTripSharingParams) (Trip, error) {
	row := q.db.QueryRow(ctx, disableTripSharing, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
	)
	return i, err
}

const enableTripSharing = `-- name: EnableTripSharing :one
UPDATE trips SET share_token = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token
`

type EnableTripSharingParams struct {
	ShareToken pgtype.Text `json:"share_token"`
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
}

func (q *Queries) EnableTripSharing(ctx context.Context, arg EnableTripSharingParams) (Trip, error) {
	row := q.db.QueryRow(ctx, enableTripSharing, arg.ShareToken, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
	)
	return i, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token FROM trips WHERE id = $1 AND user_id = $2
`

type GetTripByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByID(ctx context.Context, arg GetTripByIDParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByID, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
	)
	return i, err
}

const getTripByShareToken = `-- name: GetTripByShareToken :one
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token FROM trips WHERE share_token = $1
`

func (q *Queries) GetTripByShareToken(ctx context.Context, shareToken pgtype.Text) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByShareToken, shareToken)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
	)
	return i, err
}

const listTripsByUser = `-- name: ListTripsByUser :many
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token FROM trips
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTripsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTripsByUser(ctx context.Context, arg ListTripsByUserParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
			&i.CompletedAt,
			&i.ArchiveAfter,
			&i.ArchivedAt,
			&i.ShareToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByUserAndStatus = `-- name: ListTripsByUserAndStatus :many
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token FROM trips
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTripsByUserAndStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTripsByUserAndStatus(ctx context.Context, arg ListTripsByUserAndStatusParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
			&i.CompletedAt,
			&i.ArchiveAfter,
			&i.ArchivedAt,
			&i.ShareToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title = COALESCE(NULLIF($1::text, ''), title),
    description = COALESCE($2, description),
    status = COALESCE(NULLIF($3::text, ''), status),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    updated_at = NOW()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token
`

type UpdateTripParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
	)
	return i, err
}

const updateTripDestination = `-- name: UpdateTripDestination :execresult
UPDATE trips
SET destination_country = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
`

type UpdateTripDestinationParams struct {
	ID                 uuid.UUID   `json:"id"`
	DestinationCountry pgtype.Text `json:"destination_country"`
	UserID             uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTripDestination(ctx context.Context, arg UpdateTripDestinationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTripDestination, arg.ID, arg.DestinationCountry, arg.UserID)
}
