// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTrips = `-- name: CountActiveTrips :one
SELECT COUNT(*) FROM trips WHERE status = 'active'
`

func (q *Queries) CountActiveTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTrips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripsByUser = `-- name: CountTripsByUser :one
SELECT COUNT(*) FROM trips WHERE user_id = $1
`

func (q *Queries) CountTripsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripsByUserAndStatus = `-- name: CountTripsByUserAndStatus :one
SELECT COUNT(*) FROM trips WHERE user_id = $1 AND status = $2
`

type CountTripsByUserAndStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) CountTripsByUserAndStatus(ctx context.Context, arg CountTripsByUserAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsByUserAndStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (user_id, title, description, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector
`

type CreateTripParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = $1 AND user_id = $2
`

type DeleteTripParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTrip(ctx context.Context, arg DeleteTripParams) error {
	_, err := q.db.Exec(ctx, deleteTrip, arg.ID, arg.UserID)
	return err
}

const disableTripSharing = `-- name: DisableTripSharing :one
UPDATE trips SET share_token = NULL, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector
`

type DisableTripSharingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DisableTripSharing(ctx context.Context, arg DisableTripSharingParams) (Trip, error) {
	row := q.db.QueryRow(ctx, disableTripSharing, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const enableTripSharing = `-- name: EnableTripSharing :one
UPDATE trips SET share_token = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector
`

type EnableTripSharingParams struct {
	ShareToken pgtype.Text `json:"share_token"`
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
}

func (q *Queries) EnableTripSharing(ctx context.Context, arg EnableTripSharingParams) (Trip, error) {
	row := q.db.QueryRow(ctx, enableTripSharing, arg.ShareToken, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const getExpertCalls = `-- name: GetExpertCalls :one
SELECT expert_calls FROM trips
WHERE id = $1 AND user_id = $2
`

type GetExpertCallsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetExpertCalls(ctx context.Context, arg GetExpertCallsParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExpertCalls, arg.ID, arg.UserID)
	var expert_calls int32
	err := row.Scan(&expert_calls)
	return expert_calls, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector FROM trips WHERE id = $1 AND user_id = $2
`

type GetTripByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByID(ctx context.Context, arg GetTripByIDParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByID, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const getTripByIDOrCollaborator = `-- name: GetTripByIDOrCollaborator :one
SELECT t.id, t.user_id, t.title, t.description, t.status, t.start_date, t.end_date, t.created_at, t.updated_at, t.destination_country, t.completed_at, t.archive_after, t.archived_at, t.share_token, t.trial_started_at, t.trial_ends_at, t.destination_countries, t.expert_calls, t.search_vector FROM trips t
WHERE t.id = $1
  AND (t.user_id = $2 OR EXISTS (
    SELECT 1 FROM trip_collaborators tc
    WHERE tc.trip_id = t.id AND tc.user_id = $2 AND tc.accepted_at IS NOT NULL
  ))
`

type GetTripByIDOrCollaboratorParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByIDOrCollaborator(ctx context.Context, arg GetTripByIDOrCollaboratorParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByIDOrCollaborator, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const getTripByShareToken = `-- name: GetTripByShareToken :one
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector FROM trips WHERE share_token = $1
`

func (q *Queries) GetTripByShareToken(ctx context.Context, shareToken pgtype.Text) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByShareToken, shareToken)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const incrementExpertCalls = `-- name: IncrementExpertCalls :one
UPDATE trips SET expert_calls = expert_calls + 1, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING expert_calls
`

type IncrementExpertCallsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IncrementExpertCalls(ctx context.Context, arg IncrementExpertCallsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementExpertCalls, arg.ID, arg.UserID)
	var expert_calls int32
	err := row.Scan(&expert_calls)
	return expert_calls, err
}

const isTripTrialActive = `-- name: IsTripTrialActive :one
SELECT COALESCE(trial_ends_at > NOW(), false)::boolean AS active FROM trips WHERE id = $1
`

func (q *Queries) IsTripTrialActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isTripTrialActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listTripsByUser = `-- name: ListTripsByUser :many
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector FROM trips
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTripsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTripsByUser(ctx context.Context, arg ListTripsByUserParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
			&i.CompletedAt,
			&i.ArchiveAfter,
			&i.ArchivedAt,
			&i.ShareToken,
			&i.TrialStartedAt,
			&i.TrialEndsAt,
			&i.DestinationCountries,
			&i.ExpertCalls,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByUserAndStatus = `-- name: ListTripsByUserAndStatus :many
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector FROM trips
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTripsByUserAndStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTripsByUserAndStatus(ctx context.Context, arg ListTripsByUserAndStatusParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
			&i.CompletedAt,
			&i.ArchiveAfter,
			&i.ArchivedAt,
			&i.ShareToken,
			&i.TrialStartedAt,
			&i.TrialEndsAt,
			&i.DestinationCountries,
			&i.ExpertCalls,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTripsByUser = `-- name: SearchTripsByUser :many
SELECT id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector FROM trips
WHERE user_id = $1
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT $3
`

type SearchTripsByUserParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Query      string    `json:"query"`
	MaxResults int32     `json:"max_results"`
}

func (q *Queries) SearchTripsByUser(ctx context.Context, arg SearchTripsByUserParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, searchTripsByUser, arg.UserID, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
			&i.CompletedAt,
			&i.ArchiveAfter,
			&i.ArchivedAt,
			&i.ShareToken,
			&i.TrialStartedAt,
			&i.TrialEndsAt,
			&i.DestinationCountries,
			&i.ExpertCalls,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTripTrial = `-- name: StartTripTrial :exec
UPDATE trips SET trial_started_at = NOW(), trial_ends_at = NOW() + INTERVAL '3 days', updated_at = NOW()
WHERE id = $1 AND trial_started_at IS NULL
`

func (q *Queries) StartTripTrial(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startTripTrial, id)
	return err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title = COALESCE(NULLIF($1::text, ''), title),
    description = COALESCE($2, description),
    status = COALESCE(NULLIF($3::text, ''), status),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    updated_at = NOW()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, title, description, status, start_date, end_date, created_at, updated_at, destination_country, completed_at, archive_after, archived_at, share_token, trial_started_at, trial_ends_at, destination_countries, expert_calls, search_vector
`

type UpdateTripParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
		&i.CompletedAt,
		&i.ArchiveAfter,
		&i.ArchivedAt,
		&i.ShareToken,
		&i.TrialStartedAt,
		&i.TrialEndsAt,
		&i.DestinationCountries,
		&i.ExpertCalls,
		&i.SearchVector,
	)
	return i, err
}

const updateTripDestination = `-- name: UpdateTripDestination :execresult
UPDATE trips
SET destination_country = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
`

type UpdateTripDestinationParams struct {
	ID                 uuid.UUID   `json:"id"`
	DestinationCountry pgtype.Text `json:"destination_country"`
	UserID             uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTripDestination(ctx context.Context, arg UpdateTripDestinationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTripDestination, arg.ID, arg.DestinationCountry, arg.UserID)
}

const updateTripDestinations = `-- name: UpdateTripDestinations :execresult
UPDATE trips
SET destination_countries = $1::text[],
    destination_country = COALESCE(NULLIF($2::text, ''), destination_country),
    updated_at = NOW()
WHERE id = $3 AND user_id = $4
`

type UpdateTripDestinationsParams struct {
	DestinationCountries []string  `json:"destination_countries"`
	PrimaryCountry       string    `json:"primary_country"`
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateTripDestinations(ctx context.Context, arg UpdateTripDestinationsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTripDestinations,
		arg.DestinationCountries,
		arg.PrimaryCountry,
		arg.ID,
		arg.UserID,
	)
}
