// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: under_age_blocks.sql

package dbgen

import (
	"context"
)

const isEmailUnderAgeBlocked = `-- name: IsEmailUnderAgeBlocked :one
SELECT EXISTS (
    SELECT 1 FROM under_age_blocks WHERE email_sha256 = $1
)
`

// Returns true iff the given email hash was previously refused.
// Called from the OAuth login handlers BEFORE the user upsert, so a
// refused person can't simply retry by signing in again with the same
// Google/Facebook/Apple identity.
func (q *Queries) IsEmailUnderAgeBlocked(ctx context.Context, emailSha256 string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailUnderAgeBlocked, emailSha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordUnderAgeBlock = `-- name: RecordUnderAgeBlock :exec
INSERT INTO under_age_blocks (email_sha256, oauth_provider)
VALUES ($1, $2)
ON CONFLICT (email_sha256) DO NOTHING
`

type RecordUnderAgeBlockParams struct {
	EmailSha256   string `json:"email_sha256"`
	OauthProvider string `json:"oauth_provider"`
}

// Record that an OAuth identity was refused due to the under-18 age gate.
// ON CONFLICT DO NOTHING so re-attempts are idempotent — the table tracks
// "this email was refused", not "how many times it tried to retry".
func (q *Queries) RecordUnderAgeBlock(ctx context.Context, arg RecordUnderAgeBlockParams) error {
	_, err := q.db.Exec(ctx, recordUnderAgeBlock, arg.EmailSha256, arg.OauthProvider)
	return err
}
