// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDailyMessages = `-- name: CountDailyMessages :one
SELECT COALESCE(SUM(message_count), 0)::bigint FROM daily_usage WHERE date = CURRENT_DATE
`

func (q *Queries) CountDailyMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyMessages)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const decrementDailyUsage = `-- name: DecrementDailyUsage :exec
UPDATE daily_usage SET message_count = GREATEST(message_count - 1, 0), updated_at = NOW()
WHERE user_id = $1 AND date = CURRENT_DATE
`

func (q *Queries) DecrementDailyUsage(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementDailyUsage, userID)
	return err
}

const getDailyUsage = `-- name: GetDailyUsage :one
SELECT id, user_id, date, message_count, ai_cost_cents, created_at, updated_at FROM daily_usage
WHERE user_id = $1 AND date = $2
`

type GetDailyUsageParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Date   *time.Time `json:"date"`
}

func (q *Queries) GetDailyUsage(ctx context.Context, arg GetDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, getDailyUsage, arg.UserID, arg.Date)
	var i DailyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MessageCount,
		&i.AiCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDailyUsage = `-- name: IncrementDailyUsage :one
INSERT INTO daily_usage (user_id, date, message_count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (user_id, date)
DO UPDATE SET message_count = daily_usage.message_count + 1, updated_at = NOW()
  WHERE daily_usage.message_count < $2
RETURNING id, user_id, date, message_count, ai_cost_cents, created_at, updated_at
`

type IncrementDailyUsageParams struct {
	UserID   uuid.UUID `json:"user_id"`
	MaxCount int32     `json:"max_count"`
}

// Conditionally increment: only bumps the counter if it's below the limit.
// Returns the new row. If no row is returned, the limit was already reached.
func (q *Queries) IncrementDailyUsage(ctx context.Context, arg IncrementDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, incrementDailyUsage, arg.UserID, arg.MaxCount)
	var i DailyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MessageCount,
		&i.AiCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordAICost = `-- name: RecordAICost :exec
UPDATE daily_usage SET ai_cost_cents = ai_cost_cents + $1, updated_at = NOW()
WHERE user_id = $2 AND date = CURRENT_DATE
`

type RecordAICostParams struct {
	CostCents int32     `json:"cost_cents"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordAICost(ctx context.Context, arg RecordAICostParams) error {
	_, err := q.db.Exec(ctx, recordAICost, arg.CostCents, arg.UserID)
	return err
}
