// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDailyUsage = `-- name: GetDailyUsage :one
SELECT id, user_id, date, message_count, ai_cost_cents, created_at, updated_at FROM daily_usage
WHERE user_id = $1 AND date = $2
`

type GetDailyUsageParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Date   *time.Time `json:"date"`
}

func (q *Queries) GetDailyUsage(ctx context.Context, arg GetDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, getDailyUsage, arg.UserID, arg.Date)
	var i DailyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MessageCount,
		&i.AiCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDailyUsage = `-- name: IncrementDailyUsage :one
INSERT INTO daily_usage (user_id, date, message_count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (user_id, date)
DO UPDATE SET message_count = daily_usage.message_count + 1, updated_at = NOW()
RETURNING id, user_id, date, message_count, ai_cost_cents, created_at, updated_at
`

func (q *Queries) IncrementDailyUsage(ctx context.Context, userID uuid.UUID) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, incrementDailyUsage, userID)
	var i DailyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MessageCount,
		&i.AiCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordAICost = `-- name: RecordAICost :exec
UPDATE daily_usage SET ai_cost_cents = ai_cost_cents + $1, updated_at = NOW()
WHERE user_id = $2 AND date = CURRENT_DATE
`

type RecordAICostParams struct {
	CostCents int32     `json:"cost_cents"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordAICost(ctx context.Context, arg RecordAICostParams) error {
	_, err := q.db.Exec(ctx, recordAICost, arg.CostCents, arg.UserID)
	return err
}
