// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDailyMessages = `-- name: CountDailyMessages :one
SELECT COALESCE(SUM(message_count), 0)::bigint FROM daily_usage WHERE date = CURRENT_DATE
`

func (q *Queries) CountDailyMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyMessages)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const decrementDailyUsage = `-- name: DecrementDailyUsage :exec
UPDATE daily_usage SET message_count = GREATEST(message_count - 1, 0), updated_at = NOW()
WHERE user_id = $1 AND date = CURRENT_DATE
`

func (q *Queries) DecrementDailyUsage(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementDailyUsage, userID)
	return err
}

const getAICostByTier = `-- name: GetAICostByTier :many
SELECT
    COALESCE(u.subscription_tier, 'free') AS tier,
    COUNT(DISTINCT du.user_id)::bigint AS user_count,
    COALESCE(SUM(du.ai_cost_cents), 0)::bigint AS total_cents
FROM daily_usage du
JOIN users u ON u.id = du.user_id
WHERE du.date >= CURRENT_DATE - INTERVAL '30 days'
  AND du.ai_cost_cents > 0
GROUP BY COALESCE(u.subscription_tier, 'free')
`

type GetAICostByTierRow struct {
	Tier       string `json:"tier"`
	UserCount  int64  `json:"user_count"`
	TotalCents int64  `json:"total_cents"`
}

func (q *Queries) GetAICostByTier(ctx context.Context) ([]GetAICostByTierRow, error) {
	rows, err := q.db.Query(ctx, getAICostByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAICostByTierRow{}
	for rows.Next() {
		var i GetAICostByTierRow
		if err := rows.Scan(&i.Tier, &i.UserCount, &i.TotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageByModel = `-- name: GetAIUsageByModel :many
SELECT
    provider,
    model_tier,
    COALESCE(SUM(input_tokens), 0)::bigint AS total_input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint AS total_output_tokens,
    COALESCE(SUM(cost_cents), 0)::bigint AS total_cents,
    COUNT(*)::bigint AS request_count
FROM ai_usage
WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY provider, model_tier
`

type GetAIUsageByModelRow struct {
	Provider          string `json:"provider"`
	ModelTier         string `json:"model_tier"`
	TotalInputTokens  int64  `json:"total_input_tokens"`
	TotalOutputTokens int64  `json:"total_output_tokens"`
	TotalCents        int64  `json:"total_cents"`
	RequestCount      int64  `json:"request_count"`
}

func (q *Queries) GetAIUsageByModel(ctx context.Context) ([]GetAIUsageByModelRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageByModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAIUsageByModelRow{}
	for rows.Next() {
		var i GetAIUsageByModelRow
		if err := rows.Scan(
			&i.Provider,
			&i.ModelTier,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCents,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageCostByTier = `-- name: GetAIUsageCostByTier :many
SELECT
    user_tier AS tier,
    COALESCE(SUM(cost_cents), 0)::bigint AS total_cents,
    COUNT(*)::bigint AS request_count
FROM ai_usage
WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY user_tier
`

type GetAIUsageCostByTierRow struct {
	Tier         string `json:"tier"`
	TotalCents   int64  `json:"total_cents"`
	RequestCount int64  `json:"request_count"`
}

func (q *Queries) GetAIUsageCostByTier(ctx context.Context) ([]GetAIUsageCostByTierRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageCostByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAIUsageCostByTierRow{}
	for rows.Next() {
		var i GetAIUsageCostByTierRow
		if err := rows.Scan(&i.Tier, &i.TotalCents, &i.RequestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyAICostTotal = `-- name: GetDailyAICostTotal :one
SELECT COALESCE(SUM(ai_cost_cents), 0)::bigint FROM daily_usage WHERE date = CURRENT_DATE
`

func (q *Queries) GetDailyAICostTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDailyAICostTotal)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDailyAIUsageCost = `-- name: GetDailyAIUsageCost :one
SELECT COALESCE(SUM(cost_cents), 0)::bigint FROM ai_usage WHERE created_at >= CURRENT_DATE
`

func (q *Queries) GetDailyAIUsageCost(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDailyAIUsageCost)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDailyAIUsageCostByTier = `-- name: GetDailyAIUsageCostByTier :one
SELECT COALESCE(SUM(cost_cents), 0)::bigint FROM ai_usage WHERE created_at >= CURRENT_DATE AND user_tier = $1
`

func (q *Queries) GetDailyAIUsageCostByTier(ctx context.Context, userTier string) (int64, error) {
	row := q.db.QueryRow(ctx, getDailyAIUsageCostByTier, userTier)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDailyUsage = `-- name: GetDailyUsage :one
SELECT id, user_id, date, message_count, ai_cost_cents, created_at, updated_at FROM daily_usage
WHERE user_id = $1 AND date = $2
`

type GetDailyUsageParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Date   *time.Time `json:"date"`
}

func (q *Queries) GetDailyUsage(ctx context.Context, arg GetDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, getDailyUsage, arg.UserID, arg.Date)
	var i DailyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MessageCount,
		&i.AiCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthlyAICostTotal = `-- name: GetMonthlyAICostTotal :one
SELECT COALESCE(SUM(ai_cost_cents), 0)::bigint FROM daily_usage WHERE date >= CURRENT_DATE - INTERVAL '30 days'
`

func (q *Queries) GetMonthlyAICostTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyAICostTotal)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getMonthlyAIUsageCost = `-- name: GetMonthlyAIUsageCost :one
SELECT COALESCE(SUM(cost_cents), 0)::bigint FROM ai_usage WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'
`

func (q *Queries) GetMonthlyAIUsageCost(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyAIUsageCost)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTopAICostUsers = `-- name: GetTopAICostUsers :many
SELECT
    du.user_id,
    u.email,
    COALESCE(SUM(du.ai_cost_cents), 0)::bigint AS total_cents,
    COALESCE(SUM(du.message_count), 0)::bigint AS message_count
FROM daily_usage du
JOIN users u ON u.id = du.user_id
WHERE du.date >= CURRENT_DATE - INTERVAL '30 days'
  AND du.ai_cost_cents > 0
GROUP BY du.user_id, u.email
ORDER BY total_cents DESC
LIMIT 10
`

type GetTopAICostUsersRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	TotalCents   int64     `json:"total_cents"`
	MessageCount int64     `json:"message_count"`
}

func (q *Queries) GetTopAICostUsers(ctx context.Context) ([]GetTopAICostUsersRow, error) {
	rows, err := q.db.Query(ctx, getTopAICostUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopAICostUsersRow{}
	for rows.Next() {
		var i GetTopAICostUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.TotalCents,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopAIUsers = `-- name: GetTopAIUsers :many
SELECT
    a.user_id,
    u.email,
    COALESCE(SUM(a.cost_cents), 0)::bigint AS total_cents,
    COUNT(*)::bigint AS request_count
FROM ai_usage a
JOIN users u ON u.id = a.user_id
WHERE a.created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY a.user_id, u.email
ORDER BY total_cents DESC
LIMIT 10
`

type GetTopAIUsersRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	TotalCents   int64     `json:"total_cents"`
	RequestCount int64     `json:"request_count"`
}

func (q *Queries) GetTopAIUsers(ctx context.Context) ([]GetTopAIUsersRow, error) {
	rows, err := q.db.Query(ctx, getTopAIUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopAIUsersRow{}
	for rows.Next() {
		var i GetTopAIUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.TotalCents,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyAICostTotal = `-- name: GetWeeklyAICostTotal :one
SELECT COALESCE(SUM(ai_cost_cents), 0)::bigint FROM daily_usage WHERE date >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) GetWeeklyAICostTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWeeklyAICostTotal)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getWeeklyAIUsageCost = `-- name: GetWeeklyAIUsageCost :one
SELECT COALESCE(SUM(cost_cents), 0)::bigint FROM ai_usage WHERE created_at >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) GetWeeklyAIUsageCost(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWeeklyAIUsageCost)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementDailyUsage = `-- name: IncrementDailyUsage :one
INSERT INTO daily_usage (user_id, date, message_count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (user_id, date)
DO UPDATE SET message_count = daily_usage.message_count + 1, updated_at = NOW()
  WHERE daily_usage.message_count < $2
RETURNING id, user_id, date, message_count, ai_cost_cents, created_at, updated_at
`

type IncrementDailyUsageParams struct {
	UserID   uuid.UUID `json:"user_id"`
	MaxCount int32     `json:"max_count"`
}

// Conditionally increment: only bumps the counter if it's below the limit.
// Returns the new row. If no row is returned, the limit was already reached.
func (q *Queries) IncrementDailyUsage(ctx context.Context, arg IncrementDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, incrementDailyUsage, arg.UserID, arg.MaxCount)
	var i DailyUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MessageCount,
		&i.AiCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAIUsage = `-- name: InsertAIUsage :exec
INSERT INTO ai_usage (user_id, provider, model_tier, input_tokens, output_tokens, cost_cents, user_tier)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAIUsageParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	ModelTier    string    `json:"model_tier"`
	InputTokens  int32     `json:"input_tokens"`
	OutputTokens int32     `json:"output_tokens"`
	CostCents    int32     `json:"cost_cents"`
	UserTier     string    `json:"user_tier"`
}

func (q *Queries) InsertAIUsage(ctx context.Context, arg InsertAIUsageParams) error {
	_, err := q.db.Exec(ctx, insertAIUsage,
		arg.UserID,
		arg.Provider,
		arg.ModelTier,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostCents,
		arg.UserTier,
	)
	return err
}

const recordAICost = `-- name: RecordAICost :exec
UPDATE daily_usage SET ai_cost_cents = ai_cost_cents + $1, updated_at = NOW()
WHERE user_id = $2 AND date = CURRENT_DATE
`

type RecordAICostParams struct {
	CostCents int32     `json:"cost_cents"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordAICost(ctx context.Context, arg RecordAICostParams) error {
	_, err := q.db.Exec(ctx, recordAICost, arg.CostCents, arg.UserID)
	return err
}
