// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash
`

type CreateUserWithPasswordParams struct {
	Email        string      `json:"email"`
	Name         pgtype.Text `json:"name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
		&i.IsAdmin,
		&i.AppleSub,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
		&i.IsAdmin,
		&i.AppleSub,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
		&i.IsAdmin,
		&i.AppleSub,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
		&i.IsAdmin,
		&i.AppleSub,
		&i.PasswordHash,
	)
	return i, err
}

const getUserDefaultPersona = `-- name: GetUserDefaultPersona :one
SELECT default_persona_id FROM users WHERE id = $1
`

func (q *Queries) GetUserDefaultPersona(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserDefaultPersona, id)
	var default_persona_id pgtype.Text
	err := row.Scan(&default_persona_id)
	return default_persona_id, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT id, password_hash FROM users WHERE email = $1
`

type GetUserPasswordHashRow struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) GetUserPasswordHash(ctx context.Context, email string) (GetUserPasswordHashRow, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, email)
	var i GetUserPasswordHashRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getUserSubscriptionTier = `-- name: GetUserSubscriptionTier :one
SELECT COALESCE(subscription_tier, 'free') FROM users WHERE id = $1
`

func (q *Queries) GetUserSubscriptionTier(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionTier, id)
	var subscription_tier string
	err := row.Scan(&subscription_tier)
	return subscription_tier, err
}

const isUserAdmin = `-- name: IsUserAdmin :one

SELECT is_admin FROM users WHERE id = $1
`

// Facebook + Apple OAuth queries were removed when the project transitioned
// to self-hostable OSS (email+password default, Google OAuth optional). The
// facebook_id / apple_sub columns remain in the schema as dead fields —
// migrations are immutable history.
func (q *Queries) IsUserAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdmin, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash FROM users ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultPersonaID,
			&i.SubscriptionTier,
			&i.AgeVerifiedAt,
			&i.FacebookID,
			&i.IsAdmin,
			&i.AppleSub,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash FROM users WHERE email ILIKE '%' || $1::text || '%' OR name ILIKE '%' || $1::text || '%'
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type SearchUsersParams struct {
	Query      string `json:"query"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultPersonaID,
			&i.SubscriptionTier,
			&i.AgeVerifiedAt,
			&i.FacebookID,
			&i.IsAdmin,
			&i.AppleSub,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedAdminByEmail = `-- name: SeedAdminByEmail :exec
UPDATE users SET is_admin = true, updated_at = NOW() WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) SeedAdminByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, seedAdminByEmail, email)
	return err
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE users SET is_admin = $1, updated_at = NOW() WHERE id = $2
`

type SetAdminParams struct {
	IsAdmin bool      `json:"is_admin"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.Exec(ctx, setAdmin, arg.IsAdmin, arg.UserID)
	return err
}

const setUserDefaultPersona = `-- name: SetUserDefaultPersona :one
UPDATE users SET default_persona_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash
`

type SetUserDefaultPersonaParams struct {
	ID               uuid.UUID   `json:"id"`
	DefaultPersonaID pgtype.Text `json:"default_persona_id"`
}

func (q *Queries) SetUserDefaultPersona(ctx context.Context, arg SetUserDefaultPersonaParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDefaultPersona, arg.ID, arg.DefaultPersonaID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
		&i.IsAdmin,
		&i.AppleSub,
		&i.PasswordHash,
	)
	return i, err
}

const setUserSubscriptionTier = `-- name: SetUserSubscriptionTier :exec
UPDATE users SET subscription_tier = $1, updated_at = NOW() WHERE email = $2
`

type SetUserSubscriptionTierParams struct {
	SubscriptionTier string `json:"subscription_tier"`
	Email            string `json:"email"`
}

func (q *Queries) SetUserSubscriptionTier(ctx context.Context, arg SetUserSubscriptionTierParams) error {
	_, err := q.db.Exec(ctx, setUserSubscriptionTier, arg.SubscriptionTier, arg.Email)
	return err
}

const setUserSubscriptionTierByID = `-- name: SetUserSubscriptionTierByID :exec
UPDATE users SET subscription_tier = $1, updated_at = NOW() WHERE id = $2
`

type SetUserSubscriptionTierByIDParams struct {
	Tier   string    `json:"tier"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetUserSubscriptionTierByID(ctx context.Context, arg SetUserSubscriptionTierByIDParams) error {
	_, err := q.db.Exec(ctx, setUserSubscriptionTierByID, arg.Tier, arg.UserID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateUserPasswordHashParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	UserID       uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UserID)
	return err
}

const upsertUserByGoogleID = `-- name: UpsertUserByGoogleID :one
INSERT INTO users (google_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_id)
DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, avatar_url = EXCLUDED.avatar_url, updated_at = NOW()
RETURNING id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id, is_admin, apple_sub, password_hash
`

type UpsertUserByGoogleIDParams struct {
	GoogleID  pgtype.Text `json:"google_id"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByGoogleID,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
		&i.IsAdmin,
		&i.AppleSub,
		&i.PasswordHash,
	)
	return i, err
}
