// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithFacebook = `-- name: CreateUserWithFacebook :one
INSERT INTO users (email, name, facebook_id, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id
`

type CreateUserWithFacebookParams struct {
	Email      string      `json:"email"`
	Name       pgtype.Text `json:"name"`
	FacebookID pgtype.Text `json:"facebook_id"`
	AvatarUrl  pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUserWithFacebook(ctx context.Context, arg CreateUserWithFacebookParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithFacebook,
		arg.Email,
		arg.Name,
		arg.FacebookID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}

const getUserByFacebookID = `-- name: GetUserByFacebookID :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id FROM users WHERE facebook_id = $1
`

func (q *Queries) GetUserByFacebookID(ctx context.Context, facebookID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFacebookID, facebookID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}

const getUserDefaultPersona = `-- name: GetUserDefaultPersona :one
SELECT default_persona_id FROM users WHERE id = $1
`

func (q *Queries) GetUserDefaultPersona(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserDefaultPersona, id)
	var default_persona_id pgtype.Text
	err := row.Scan(&default_persona_id)
	return default_persona_id, err
}

const getUserSubscriptionTier = `-- name: GetUserSubscriptionTier :one
SELECT COALESCE(subscription_tier, 'free') FROM users WHERE id = $1
`

func (q *Queries) GetUserSubscriptionTier(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionTier, id)
	var subscription_tier string
	err := row.Scan(&subscription_tier)
	return subscription_tier, err
}

const isAgeVerified = `-- name: IsAgeVerified :one
SELECT COALESCE(age_verified_at IS NOT NULL, false)::boolean AS verified FROM users WHERE id = $1
`

func (q *Queries) IsAgeVerified(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAgeVerified, id)
	var verified bool
	err := row.Scan(&verified)
	return verified, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id FROM users ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultPersonaID,
			&i.SubscriptionTier,
			&i.AgeVerifiedAt,
			&i.FacebookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id FROM users WHERE email ILIKE '%' || $1::text || '%' OR name ILIKE '%' || $1::text || '%'
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type SearchUsersParams struct {
	Query      string `json:"query"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultPersonaID,
			&i.SubscriptionTier,
			&i.AgeVerifiedAt,
			&i.FacebookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgeVerified = `-- name: SetAgeVerified :exec
UPDATE users SET age_verified_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetAgeVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAgeVerified, id)
	return err
}

const setUserDefaultPersona = `-- name: SetUserDefaultPersona :one
UPDATE users SET default_persona_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id
`

type SetUserDefaultPersonaParams struct {
	ID               uuid.UUID   `json:"id"`
	DefaultPersonaID pgtype.Text `json:"default_persona_id"`
}

func (q *Queries) SetUserDefaultPersona(ctx context.Context, arg SetUserDefaultPersonaParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDefaultPersona, arg.ID, arg.DefaultPersonaID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}

const setUserSubscriptionTier = `-- name: SetUserSubscriptionTier :exec
UPDATE users SET subscription_tier = $1, updated_at = NOW() WHERE email = $2
`

type SetUserSubscriptionTierParams struct {
	SubscriptionTier string `json:"subscription_tier"`
	Email            string `json:"email"`
}

func (q *Queries) SetUserSubscriptionTier(ctx context.Context, arg SetUserSubscriptionTierParams) error {
	_, err := q.db.Exec(ctx, setUserSubscriptionTier, arg.SubscriptionTier, arg.Email)
	return err
}

const updateUserFacebookID = `-- name: UpdateUserFacebookID :exec
UPDATE users SET facebook_id = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserFacebookIDParams struct {
	ID         uuid.UUID   `json:"id"`
	FacebookID pgtype.Text `json:"facebook_id"`
}

func (q *Queries) UpdateUserFacebookID(ctx context.Context, arg UpdateUserFacebookIDParams) error {
	_, err := q.db.Exec(ctx, updateUserFacebookID, arg.ID, arg.FacebookID)
	return err
}

const upsertUserByGoogleID = `-- name: UpsertUserByGoogleID :one
INSERT INTO users (google_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_id)
DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, avatar_url = EXCLUDED.avatar_url, updated_at = NOW()
RETURNING id, email, name, google_id, avatar_url, created_at, updated_at, default_persona_id, subscription_tier, age_verified_at, facebook_id
`

type UpsertUserByGoogleIDParams struct {
	GoogleID  string      `json:"google_id"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByGoogleID,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultPersonaID,
		&i.SubscriptionTier,
		&i.AgeVerifiedAt,
		&i.FacebookID,
	)
	return i, err
}
