// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToWaitlist = `-- name: AddToWaitlist :one
INSERT INTO waitlist (email)
VALUES ($1)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, invite_code, signed_up_at, invited_at, accepted_at
`

func (q *Queries) AddToWaitlist(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRow(ctx, addToWaitlist, email)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitlistAhead = `-- name: CountWaitlistAhead :one
SELECT COUNT(*) FROM waitlist
WHERE signed_up_at < $1
AND accepted_at IS NULL
`

func (q *Queries) CountWaitlistAhead(ctx context.Context, signedUpAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistAhead, signedUpAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWaitlistByEmail = `-- name: GetWaitlistByEmail :one
SELECT id, email, invite_code, signed_up_at, invited_at, accepted_at FROM waitlist WHERE email = $1
`

func (q *Queries) GetWaitlistByEmail(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistByEmail, email)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getWaitlistByInviteCode = `-- name: GetWaitlistByInviteCode :one
SELECT id, email, invite_code, signed_up_at, invited_at, accepted_at FROM waitlist WHERE invite_code = $1
`

func (q *Queries) GetWaitlistByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistByInviteCode, inviteCode)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const markWaitlistAccepted = `-- name: MarkWaitlistAccepted :exec
UPDATE waitlist SET accepted_at = NOW()
WHERE email = $1
`

func (q *Queries) MarkWaitlistAccepted(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, markWaitlistAccepted, email)
	return err
}
