// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToWaitlist = `-- name: AddToWaitlist :one
INSERT INTO waitlist (email, verify_token)
VALUES ($1, $2)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, invite_code, signed_up_at, invited_at, accepted_at, verify_token, verified_at
`

type AddToWaitlistParams struct {
	Email       string      `json:"email"`
	VerifyToken pgtype.Text `json:"verify_token"`
}

func (q *Queries) AddToWaitlist(ctx context.Context, arg AddToWaitlistParams) (Waitlist, error) {
	row := q.db.QueryRow(ctx, addToWaitlist, arg.Email, arg.VerifyToken)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.VerifyToken,
		&i.VerifiedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitlist = `-- name: CountWaitlist :one
SELECT COUNT(*) FROM waitlist WHERE verified_at IS NOT NULL
`

func (q *Queries) CountWaitlist(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlist)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitlistAhead = `-- name: CountWaitlistAhead :one
SELECT COUNT(*) FROM waitlist
WHERE signed_up_at < $1
AND accepted_at IS NULL
AND verified_at IS NOT NULL
`

func (q *Queries) CountWaitlistAhead(ctx context.Context, signedUpAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistAhead, signedUpAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWaitlistByEmail = `-- name: GetWaitlistByEmail :one
SELECT id, email, invite_code, signed_up_at, invited_at, accepted_at, verify_token, verified_at FROM waitlist WHERE email = $1
`

func (q *Queries) GetWaitlistByEmail(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistByEmail, email)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.VerifyToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getWaitlistByInviteCode = `-- name: GetWaitlistByInviteCode :one
SELECT id, email, invite_code, signed_up_at, invited_at, accepted_at, verify_token, verified_at FROM waitlist WHERE invite_code = $1
`

func (q *Queries) GetWaitlistByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistByInviteCode, inviteCode)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.VerifyToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getWaitlistByVerifyToken = `-- name: GetWaitlistByVerifyToken :one
SELECT id, email, invite_code, signed_up_at, invited_at, accepted_at, verify_token, verified_at FROM waitlist WHERE verify_token = $1
`

func (q *Queries) GetWaitlistByVerifyToken(ctx context.Context, verifyToken pgtype.Text) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistByVerifyToken, verifyToken)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.VerifyToken,
		&i.VerifiedAt,
	)
	return i, err
}

const listWaitlist = `-- name: ListWaitlist :many
SELECT id, email, invite_code, signed_up_at, invited_at, accepted_at, verify_token, verified_at FROM waitlist ORDER BY signed_up_at ASC
LIMIT $2 OFFSET $1
`

type ListWaitlistParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListWaitlist(ctx context.Context, arg ListWaitlistParams) ([]Waitlist, error) {
	rows, err := q.db.Query(ctx, listWaitlist, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Waitlist{}
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.InviteCode,
			&i.SignedUpAt,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.VerifyToken,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWaitlistAccepted = `-- name: MarkWaitlistAccepted :exec
UPDATE waitlist SET accepted_at = NOW()
WHERE email = $1
`

func (q *Queries) MarkWaitlistAccepted(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, markWaitlistAccepted, email)
	return err
}

const setWaitlistInviteCode = `-- name: SetWaitlistInviteCode :exec
UPDATE waitlist SET invite_code = $1, invited_at = NOW()
WHERE email = $2
`

type SetWaitlistInviteCodeParams struct {
	InviteCode pgtype.Text `json:"invite_code"`
	Email      string      `json:"email"`
}

func (q *Queries) SetWaitlistInviteCode(ctx context.Context, arg SetWaitlistInviteCodeParams) error {
	_, err := q.db.Exec(ctx, setWaitlistInviteCode, arg.InviteCode, arg.Email)
	return err
}

const verifyWaitlistEmail = `-- name: VerifyWaitlistEmail :one
UPDATE waitlist SET verified_at = NOW()
WHERE verify_token = $1 AND verified_at IS NULL
RETURNING id, email, invite_code, signed_up_at, invited_at, accepted_at, verify_token, verified_at
`

func (q *Queries) VerifyWaitlistEmail(ctx context.Context, verifyToken pgtype.Text) (Waitlist, error) {
	row := q.db.QueryRow(ctx, verifyWaitlistEmail, verifyToken)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteCode,
		&i.SignedUpAt,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.VerifyToken,
		&i.VerifiedAt,
	)
	return i, err
}
