// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"
	"time"
)

const getFunnelMetrics = `-- name: GetFunnelMetrics :one
SELECT
  (SELECT COUNT(*) FROM users WHERE created_at >= $1::timestamptz)::bigint AS total_signups,
  (SELECT COUNT(DISTINCT user_id) FROM trips WHERE created_at >= $1::timestamptz)::bigint AS activated,
  (SELECT COUNT(DISTINCT t.user_id) FROM trips t WHERE t.created_at >= $1::timestamptz AND (SELECT COUNT(*) FROM itinerary_items ii WHERE ii.trip_id = t.id) >= 5)::bigint AS engaged,
  (SELECT COUNT(DISTINCT user_id) FROM trip_unlocks WHERE source = 'purchase' AND unlocked_at >= $1::timestamptz)::bigint AS paid_trip_pro,
  (SELECT COUNT(DISTINCT user_id) FROM subscriptions WHERE status = 'active' AND created_at >= $1::timestamptz)::bigint AS paid_subscription
`

type GetFunnelMetricsRow struct {
	TotalSignups     int64 `json:"total_signups"`
	Activated        int64 `json:"activated"`
	Engaged          int64 `json:"engaged"`
	PaidTripPro      int64 `json:"paid_trip_pro"`
	PaidSubscription int64 `json:"paid_subscription"`
}

// Conversion funnel: signups -> activated (created a trip) -> engaged (5+ itinerary items) -> paid.
func (q *Queries) GetFunnelMetrics(ctx context.Context, since time.Time) (GetFunnelMetricsRow, error) {
	row := q.db.QueryRow(ctx, getFunnelMetrics, since)
	var i GetFunnelMetricsRow
	err := row.Scan(
		&i.TotalSignups,
		&i.Activated,
		&i.Engaged,
		&i.PaidTripPro,
		&i.PaidSubscription,
	)
	return i, err
}

const getRetentionCohorts = `-- name: GetRetentionCohorts :many
SELECT
  date_trunc('week', u.created_at)::date AS cohort_week,
  COUNT(DISTINCT u.id)::bigint AS cohort_size,
  COUNT(DISTINCT CASE WHEN du.date BETWEEN u.created_at::date AND u.created_at::date + 1 THEN du.user_id END)::bigint AS d1_active,
  COUNT(DISTINCT CASE WHEN du.date BETWEEN u.created_at::date AND u.created_at::date + 7 THEN du.user_id END)::bigint AS d7_active,
  COUNT(DISTINCT CASE WHEN du.date BETWEEN u.created_at::date AND u.created_at::date + 30 THEN du.user_id END)::bigint AS d30_active
FROM users u
LEFT JOIN daily_usage du ON du.user_id = u.id
WHERE u.created_at >= $1::timestamptz
GROUP BY cohort_week
ORDER BY cohort_week DESC
`

type GetRetentionCohortsRow struct {
	CohortWeek *time.Time `json:"cohort_week"`
	CohortSize int64      `json:"cohort_size"`
	D1Active   int64      `json:"d1_active"`
	D7Active   int64      `json:"d7_active"`
	D30Active  int64      `json:"d30_active"`
}

// Weekly cohort retention: users who signed up in a given week and were active N days later.
// "Active" = sent at least one chat message (has a row in daily_usage for that period).
func (q *Queries) GetRetentionCohorts(ctx context.Context, since time.Time) ([]GetRetentionCohortsRow, error) {
	rows, err := q.db.Query(ctx, getRetentionCohorts, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRetentionCohortsRow{}
	for rows.Next() {
		var i GetRetentionCohortsRow
		if err := rows.Scan(
			&i.CohortWeek,
			&i.CohortSize,
			&i.D1Active,
			&i.D7Active,
			&i.D30Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
