// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, trip_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, departure_location, arrival_location, num_guests, price_cents, currency, timezone)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type CreateBookingParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	TripID            pgtype.UUID        `json:"trip_id"`
	Type              string             `json:"type"`
	ConfirmationCode  pgtype.Text        `json:"confirmation_code"`
	Provider          pgtype.Text        `json:"provider"`
	Title             string             `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Location          interface{}        `json:"location"`
	Address           pgtype.Text        `json:"address"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         pgtype.Text        `json:"raw_source"`
	Source            string             `json:"source"`
	DepartureLocation pgtype.Text        `json:"departure_location"`
	ArrivalLocation   pgtype.Text        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
	PriceCents        pgtype.Int8        `json:"price_cents"`
	Currency          pgtype.Text        `json:"currency"`
	Timezone          pgtype.Text        `json:"timezone"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.TripID,
		arg.Type,
		arg.ConfirmationCode,
		arg.Provider,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Address,
		arg.DetailsJson,
		arg.RawSource,
		arg.Source,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
		arg.PriceCents,
		arg.Currency,
		arg.Timezone,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingForOwnerOrEditor = `-- name: CreateBookingForOwnerOrEditor :one
INSERT INTO bookings (user_id, trip_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, departure_location, arrival_location, num_guests, price_cents, currency, timezone)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
WHERE $2::uuid IS NULL
   OR EXISTS (
     SELECT 1 FROM trips t
     WHERE t.id = $2::uuid
       AND (
         t.user_id = $1
         OR EXISTS (
           SELECT 1 FROM trip_collaborators tc
           WHERE tc.trip_id = t.id
             AND tc.user_id = $1
             AND tc.accepted_at IS NOT NULL
             AND tc.role = 'editor'
         )
       )
   )
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type CreateBookingForOwnerOrEditorParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	TripID            pgtype.UUID        `json:"trip_id"`
	Type              string             `json:"type"`
	ConfirmationCode  pgtype.Text        `json:"confirmation_code"`
	Provider          pgtype.Text        `json:"provider"`
	Title             string             `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Location          interface{}        `json:"location"`
	Address           pgtype.Text        `json:"address"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         pgtype.Text        `json:"raw_source"`
	Source            string             `json:"source"`
	DepartureLocation pgtype.Text        `json:"departure_location"`
	ArrivalLocation   pgtype.Text        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
	PriceCents        pgtype.Int8        `json:"price_cents"`
	Currency          pgtype.Text        `json:"currency"`
	Timezone          pgtype.Text        `json:"timezone"`
}

// Authz-gated booking insert used by IngestBooking (#361 P1 fix).
// When trip_id is non-NULL, the WHERE clause re-checks that
// user_id = $1 can edit the target trip — either owns it or is an
// accepted editor-role collaborator. A malicious client passing
// another user's trip_id misses the predicate, INSERT returns zero
// rows, pgx returns ErrNoRows, the service maps that to
// trip.ErrNotOwnerOrEditor.
//
// When trip_id is NULL (unattached booking) the OR branch lets the
// insert through unchanged — unattached bookings are self-scoped
// and no trip-level check applies.
//
// AUTHZ PREDICATE: semantic duplicate of the four other
// *ForOwnerOrEditor queries across bookings.sql + itinerary.sql.
// Keep in lockstep (#353 drift warning).
func (q *Queries) CreateBookingForOwnerOrEditor(ctx context.Context, arg CreateBookingForOwnerOrEditorParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBookingForOwnerOrEditor,
		arg.UserID,
		arg.TripID,
		arg.Type,
		arg.ConfirmationCode,
		arg.Provider,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Address,
		arg.DetailsJson,
		arg.RawSource,
		arg.Source,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
		arg.PriceCents,
		arg.Currency,
		arg.Timezone,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :execrows
DELETE FROM bookings WHERE id = $1 AND user_id = $2
`

type DeleteBookingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBooking(ctx context.Context, arg DeleteBookingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBooking, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBookingByConfirmationCode = `-- name: FindBookingByConfirmationCode :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1 AND trip_id = $2
  AND confirmation_code = $3
  AND confirmation_code != ''
LIMIT 1
`

type FindBookingByConfirmationCodeParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	TripID           pgtype.UUID `json:"trip_id"`
	ConfirmationCode pgtype.Text `json:"confirmation_code"`
}

func (q *Queries) FindBookingByConfirmationCode(ctx context.Context, arg FindBookingByConfirmationCodeParams) (Booking, error) {
	row := q.db.QueryRow(ctx, findBookingByConfirmationCode, arg.UserID, arg.TripID, arg.ConfirmationCode)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const findBookingFuzzy = `-- name: FindBookingFuzzy :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1
  AND trip_id = $2
  AND type = $3
  AND start_time IS NOT NULL
  AND ABS(EXTRACT(EPOCH FROM (start_time - $4))) <= 7 * 86400
ORDER BY ABS(EXTRACT(EPOCH FROM (start_time - $4)))
LIMIT 1
`

type FindBookingFuzzyParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TripID    pgtype.UUID        `json:"trip_id"`
	Type      string             `json:"type"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

// Fuzzy duplicate detection: same user + trip + type + start_time within 7 days.
// Used as a fallback when confirmation_code is absent or didn't match.
// Ordered by closest time delta so the nearest match wins on ties.
func (q *Queries) FindBookingFuzzy(ctx context.Context, arg FindBookingFuzzyParams) (Booking, error) {
	row := q.db.QueryRow(ctx, findBookingFuzzy,
		arg.UserID,
		arg.TripID,
		arg.Type,
		arg.StartTime,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings WHERE id = $1 AND user_id = $2
`

type GetBookingByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, arg.ID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripCostSummary = `-- name: GetTripCostSummary :many
SELECT
  COALESCE(currency, 'USD') AS currency,
  SUM(price_cents) AS total_cents,
  COUNT(*) AS booking_count
FROM bookings
WHERE trip_id = $1 AND user_id = $2
  AND price_cents IS NOT NULL AND price_cents > 0
GROUP BY currency
ORDER BY total_cents DESC
`

type GetTripCostSummaryParams struct {
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

type GetTripCostSummaryRow struct {
	Currency     string `json:"currency"`
	TotalCents   int64  `json:"total_cents"`
	BookingCount int64  `json:"booking_count"`
}

func (q *Queries) GetTripCostSummary(ctx context.Context, arg GetTripCostSummaryParams) ([]GetTripCostSummaryRow, error) {
	rows, err := q.db.Query(ctx, getTripCostSummary, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTripCostSummaryRow{}
	for rows.Next() {
		var i GetTripCostSummaryRow
		if err := rows.Scan(&i.Currency, &i.TotalCents, &i.BookingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkBookingToTrip = `-- name: LinkBookingToTrip :one
UPDATE bookings SET trip_id = $2
WHERE id = $1 AND user_id = $3
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type LinkBookingToTripParams struct {
	ID     uuid.UUID   `json:"id"`
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) LinkBookingToTrip(ctx context.Context, arg LinkBookingToTripParams) (Booking, error) {
	row := q.db.QueryRow(ctx, linkBookingToTrip, arg.ID, arg.TripID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const linkBookingToTripForOwnerOrEditor = `-- name: LinkBookingToTripForOwnerOrEditor :one
UPDATE bookings b SET trip_id = $2
WHERE b.id = $1
  AND b.user_id = $3
  AND EXISTS (
    SELECT 1 FROM trips t
    WHERE t.id = $2
      AND (
        t.user_id = $3
        OR EXISTS (
          SELECT 1 FROM trip_collaborators tc
          WHERE tc.trip_id = t.id
            AND tc.user_id = $3
            AND tc.accepted_at IS NOT NULL
            AND tc.role = 'editor'
        )
      )
  )
RETURNING b.id, b.trip_id, b.user_id, b.type, b.confirmation_code, b.provider, b.title, b.start_time, b.end_time, b.location, b.address, b.details_json, b.raw_source, b.source, b.created_at, b.departure_location, b.arrival_location, b.num_guests, b.price_cents, b.currency, b.timezone, b.updated_at
`

type LinkBookingToTripForOwnerOrEditorParams struct {
	ID     uuid.UUID   `json:"id"`
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

// Authz-gated re-link of a booking to a trip (#361 P1 fix).
// The plain LinkBookingToTrip above only gated on booking.user_id
// so a user could re-associate their own booking with a victim's
// trip. Here the UPDATE requires both booking ownership AND edit
// rights on the target trip. Predicate miss → pgx.ErrNoRows →
// trip.ErrNotOwnerOrEditor.
func (q *Queries) LinkBookingToTripForOwnerOrEditor(ctx context.Context, arg LinkBookingToTripForOwnerOrEditorParams) (Booking, error) {
	row := q.db.QueryRow(ctx, linkBookingToTripForOwnerOrEditor, arg.ID, arg.TripID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByTrip = `-- name: ListBookingsByTrip :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE trip_id = $1 AND user_id = $2
ORDER BY start_time
`

type ListBookingsByTripParams struct {
	TripID pgtype.UUID `json:"trip_id"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) ListBookingsByTrip(ctx context.Context, arg ListBookingsByTripParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByTrip, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
			&i.PriceCents,
			&i.Currency,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
			&i.PriceCents,
			&i.Currency,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeBooking = `-- name: MergeBooking :one
UPDATE bookings SET
  confirmation_code = COALESCE(NULLIF($1, ''), confirmation_code),
  provider          = COALESCE(NULLIF($2, ''), provider),
  title             = COALESCE(NULLIF($3, ''), title),
  start_time        = COALESCE($4, start_time),
  end_time          = COALESCE($5, end_time),
  address           = COALESCE(NULLIF($6, ''), address),
  departure_location = COALESCE(NULLIF($7, ''), departure_location),
  arrival_location  = COALESCE(NULLIF($8, ''), arrival_location),
  num_guests        = COALESCE($9, num_guests),
  price_cents       = COALESCE($10, price_cents),
  currency          = COALESCE(NULLIF($11, ''), currency),
  timezone          = COALESCE(NULLIF($12, ''), timezone),
  details_json      = COALESCE($13, details_json),
  raw_source        = COALESCE(NULLIF($14, ''), raw_source),
  updated_at        = NOW()
WHERE id = $15
  AND user_id = $16
  AND trip_id = $17
  AND updated_at <= created_at + interval '1 second'
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type MergeBookingParams struct {
	ConfirmationCode  interface{}        `json:"confirmation_code"`
	Provider          interface{}        `json:"provider"`
	Title             interface{}        `json:"title"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Address           interface{}        `json:"address"`
	DepartureLocation interface{}        `json:"departure_location"`
	ArrivalLocation   interface{}        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
	PriceCents        pgtype.Int8        `json:"price_cents"`
	Currency          interface{}        `json:"currency"`
	Timezone          interface{}        `json:"timezone"`
	DetailsJson       []byte             `json:"details_json"`
	RawSource         interface{}        `json:"raw_source"`
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	TripID            pgtype.UUID        `json:"trip_id"`
}

// Merge a re-imported booking into an existing record. All non-empty/non-null
// values from the new import overwrite the stored values; existing data is
// preserved when the new import omits a field (COALESCE pattern).
//
// The WHERE clause locks the merge to four invariants:
//
//	id + user_id  — base ownership check;
//	trip_id       — defense-in-depth so a future caller cannot merge a
//	                booking from one trip into a booking on another even
//	                if the SELECT phase is bypassed;
//	updated_at <= created_at + interval '1 second'  — preserves user
//	                edits. If the user has touched the booking via
//	                UpdateBooking after creation, updated_at moves and
//	                this predicate fails, the merge no-ops, the service
//	                returns the existing record unchanged. Stops a
//	                re-imported confirmation from silently clobbering a
//	                user's manual edits to title / address / details_json
//	                / etc.
//
// Predicate miss → pgx.ErrNoRows. Callers must distinguish "user-edited
// or trip mismatch" (preserve existing) from "row vanished" (real error).
//
// `type` is deliberately NOT COALESCE'd. The AI parser can reclassify
// the same confirmation as "hotel" one run and "vacation_rental" the
// next, and silently mutating it would break the frontend's type-keyed
// details renderer for that booking (the oneof in proto's Booking
// message would point to a payload that doesn't match the new type).
// Type can only change via explicit UpdateBooking from a user action.
func (q *Queries) MergeBooking(ctx context.Context, arg MergeBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, mergeBooking,
		arg.ConfirmationCode,
		arg.Provider,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Address,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
		arg.PriceCents,
		arg.Currency,
		arg.Timezone,
		arg.DetailsJson,
		arg.RawSource,
		arg.ID,
		arg.UserID,
		arg.TripID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const searchBookings = `-- name: SearchBookings :many
SELECT id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at FROM bookings
WHERE user_id = $1
  AND (title ILIKE '%' || $2 || '%' OR provider ILIKE '%' || $2 || '%' OR confirmation_code ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3
`

type SearchBookingsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Query      pgtype.Text `json:"query"`
	MaxResults int32       `json:"max_results"`
}

func (q *Queries) SearchBookings(ctx context.Context, arg SearchBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, searchBookings, arg.UserID, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Type,
			&i.ConfirmationCode,
			&i.Provider,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Address,
			&i.DetailsJson,
			&i.RawSource,
			&i.Source,
			&i.CreatedAt,
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.NumGuests,
			&i.PriceCents,
			&i.Currency,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings SET
  title = COALESCE(NULLIF($1, ''), title),
  type = COALESCE(NULLIF($2, ''), type),
  confirmation_code = COALESCE(NULLIF($3, ''), confirmation_code),
  provider = COALESCE(NULLIF($4, ''), provider),
  start_time = COALESCE($5, start_time),
  end_time = COALESCE($6, end_time),
  address = COALESCE(NULLIF($7, ''), address),
  departure_location = COALESCE(NULLIF($8, ''), departure_location),
  arrival_location = COALESCE(NULLIF($9, ''), arrival_location),
  num_guests = COALESCE($10, num_guests),
  price_cents = COALESCE($11, price_cents),
  currency = COALESCE(NULLIF($12, ''), currency),
  timezone = COALESCE(NULLIF($13, ''), timezone),
  updated_at = NOW()
WHERE id = $14 AND user_id = $15
RETURNING id, trip_id, user_id, type, confirmation_code, provider, title, start_time, end_time, location, address, details_json, raw_source, source, created_at, departure_location, arrival_location, num_guests, price_cents, currency, timezone, updated_at
`

type UpdateBookingParams struct {
	Title             interface{}        `json:"title"`
	Type              interface{}        `json:"type"`
	ConfirmationCode  interface{}        `json:"confirmation_code"`
	Provider          interface{}        `json:"provider"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Address           interface{}        `json:"address"`
	DepartureLocation interface{}        `json:"departure_location"`
	ArrivalLocation   interface{}        `json:"arrival_location"`
	NumGuests         pgtype.Int4        `json:"num_guests"`
	PriceCents        pgtype.Int8        `json:"price_cents"`
	Currency          interface{}        `json:"currency"`
	Timezone          interface{}        `json:"timezone"`
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking,
		arg.Title,
		arg.Type,
		arg.ConfirmationCode,
		arg.Provider,
		arg.StartTime,
		arg.EndTime,
		arg.Address,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.NumGuests,
		arg.PriceCents,
		arg.Currency,
		arg.Timezone,
		arg.ID,
		arg.UserID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Type,
		&i.ConfirmationCode,
		&i.Provider,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Address,
		&i.DetailsJson,
		&i.RawSource,
		&i.Source,
		&i.CreatedAt,
		&i.DepartureLocation,
		&i.ArrivalLocation,
		&i.NumGuests,
		&i.PriceCents,
		&i.Currency,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
