// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (id, user_id, trip_id, mode, created_at, last_message_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, user_id, trip_id, mode, created_at, last_message_at, message_count, expire_at, summary, summary_message_count
`

type CreateChatSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TripID    string    `json:"trip_id"`
	Mode      string    `json:"mode"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession,
		arg.ID,
		arg.UserID,
		arg.TripID,
		arg.Mode,
		arg.CreatedAt,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.Mode,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.ExpireAt,
		&i.Summary,
		&i.SummaryMessageCount,
	)
	return i, err
}

const deleteChatForTrip = `-- name: DeleteChatForTrip :exec
DELETE FROM chat_sessions
WHERE trip_id = $1
`

// DeleteChatForTrip removes ALL chat for a trip, across every participant.
// Used when the trip itself is deleted.
func (q *Queries) DeleteChatForTrip(ctx context.Context, tripID string) error {
	_, err := q.db.Exec(ctx, deleteChatForTrip, tripID)
	return err
}

const deleteChatMessage = `-- name: DeleteChatMessage :exec
DELETE FROM chat_messages m
USING chat_sessions s
WHERE m.id = $1 AND m.session_id = $2
  AND s.id = m.session_id AND s.user_id = $3 AND s.trip_id = $4
`

type DeleteChatMessageParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	TripID    string    `json:"trip_id"`
}

func (q *Queries) DeleteChatMessage(ctx context.Context, arg DeleteChatMessageParams) error {
	_, err := q.db.Exec(ctx, deleteChatMessage,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.TripID,
	)
	return err
}

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE FROM chat_sessions
WHERE id = $1 AND user_id = $2 AND trip_id = $3
`

type DeleteChatSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	TripID string    `json:"trip_id"`
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error {
	_, err := q.db.Exec(ctx, deleteChatSession, arg.ID, arg.UserID, arg.TripID)
	return err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, trip_id, mode, created_at, last_message_at, message_count, expire_at, summary, summary_message_count FROM chat_sessions
WHERE id = $1 AND user_id = $2 AND trip_id = $3
`

type GetChatSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	TripID string    `json:"trip_id"`
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, arg.ID, arg.UserID, arg.TripID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.Mode,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.ExpireAt,
		&i.Summary,
		&i.SummaryMessageCount,
	)
	return i, err
}

const getNewestChatMessages = `-- name: GetNewestChatMessages :many
SELECT m.id, m.session_id, m.seq, m.role, m.content, m.metadata, m.tool_calls, m.tool_results, m.created_at FROM chat_messages m
JOIN chat_sessions s ON s.id = m.session_id
WHERE m.session_id = $1 AND s.user_id = $2 AND s.trip_id = $3
ORDER BY m.seq DESC
LIMIT $4
`

type GetNewestChatMessagesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	TripID    string    `json:"trip_id"`
	Limit     int32     `json:"limit"`
}

// GetNewestChatMessages returns the newest N messages in reverse-chronological
// order; the store reverses them to chronological. The join enforces that the
// session belongs to the given user and trip.
func (q *Queries) GetNewestChatMessages(ctx context.Context, arg GetNewestChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getNewestChatMessages,
		arg.SessionID,
		arg.UserID,
		arg.TripID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.ToolCalls,
			&i.ToolResults,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOldestChatMessages = `-- name: GetOldestChatMessages :many
SELECT m.id, m.session_id, m.seq, m.role, m.content, m.metadata, m.tool_calls, m.tool_results, m.created_at FROM chat_messages m
JOIN chat_sessions s ON s.id = m.session_id
WHERE m.session_id = $1 AND s.user_id = $2 AND s.trip_id = $3
ORDER BY m.seq ASC
LIMIT $4
`

type GetOldestChatMessagesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	TripID    string    `json:"trip_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetOldestChatMessages(ctx context.Context, arg GetOldestChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getOldestChatMessages,
		arg.SessionID,
		arg.UserID,
		arg.TripID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.ToolCalls,
			&i.ToolResults,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatMessage = `-- name: InsertChatMessage :exec
INSERT INTO chat_messages (id, session_id, role, content, metadata, tool_calls, tool_results, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertChatMessageParams struct {
	ID          uuid.UUID `json:"id"`
	SessionID   uuid.UUID `json:"session_id"`
	Role        string    `json:"role"`
	Content     string    `json:"content"`
	Metadata    []byte    `json:"metadata"`
	ToolCalls   []byte    `json:"tool_calls"`
	ToolResults []byte    `json:"tool_results"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) error {
	_, err := q.db.Exec(ctx, insertChatMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Metadata,
		arg.ToolCalls,
		arg.ToolResults,
		arg.CreatedAt,
	)
	return err
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT id, user_id, trip_id, mode, created_at, last_message_at, message_count, expire_at, summary, summary_message_count FROM chat_sessions
WHERE user_id = $1 AND trip_id = $2
ORDER BY last_message_at DESC
LIMIT $3
`

type ListChatSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	TripID string    `json:"trip_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessions, arg.UserID, arg.TripID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TripID,
			&i.Mode,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.ExpireAt,
			&i.Summary,
			&i.SummaryMessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveChatSessionToTrip = `-- name: MoveChatSessionToTrip :execrows
UPDATE chat_sessions
SET trip_id = $1
WHERE id = $2 AND user_id = $3 AND trip_id = $4
`

type MoveChatSessionToTripParams struct {
	ToTripID   string    `json:"to_trip_id"`
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	FromTripID string    `json:"from_trip_id"`
}

func (q *Queries) MoveChatSessionToTrip(ctx context.Context, arg MoveChatSessionToTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveChatSessionToTrip,
		arg.ToTripID,
		arg.ID,
		arg.UserID,
		arg.FromTripID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredChatSessions = `-- name: PurgeExpiredChatSessions :execrows
DELETE FROM chat_sessions
WHERE expire_at IS NOT NULL AND expire_at < NOW()
`

// PurgeExpiredChatSessions enforces chat retention: sessions past their
// expire_at are deleted (messages cascade). Run periodically by the
// lifecycle background jobs.
func (q *Queries) PurgeExpiredChatSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredChatSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeStaleLobbyChatSessions = `-- name: PurgeStaleLobbyChatSessions :execrows
DELETE FROM chat_sessions
WHERE trip_id = '_lobby'
  AND last_message_at < NOW() - make_interval(days => $1::int)
`

// PurgeStaleLobbyChatSessions deletes selection-mode ("_lobby") sessions
// idle longer than the retention window. Lobby sessions never belong to a
// trip, so they never get an expire_at stamp at trip completion — without
// this they would live until account deletion.
func (q *Queries) PurgeStaleLobbyChatSessions(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleLobbyChatSessions, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChatTTLForTrip = `-- name: SetChatTTLForTrip :exec
UPDATE chat_sessions
SET expire_at = $2
WHERE trip_id = $1
`

type SetChatTTLForTripParams struct {
	TripID   string             `json:"trip_id"`
	ExpireAt pgtype.Timestamptz `json:"expire_at"`
}

// SetChatTTLForTrip stamps the retention deadline on ALL of a trip's
// sessions, across every participant — collaborators' chat is trip data
// and follows the trip's retention, not just the owner's sessions.
func (q *Queries) SetChatTTLForTrip(ctx context.Context, arg SetChatTTLForTripParams) error {
	_, err := q.db.Exec(ctx, setChatTTLForTrip, arg.TripID, arg.ExpireAt)
	return err
}

const stampMissingChatTTLForEndedTrips = `-- name: StampMissingChatTTLForEndedTrips :execrows
UPDATE chat_sessions cs
SET expire_at = NOW() + make_interval(days => $1::int)
FROM trips t
WHERE t.id::text = cs.trip_id
  AND t.status IN ('completed', 'archived')
  AND cs.expire_at IS NULL
`

// StampMissingChatTTLForEndedTrips is the hourly safety net: any session
// belonging to a completed/archived trip that has no expire_at yet gets
// one. Catches sessions created after the completion stamp, collaborator
// sessions, and stamps that failed at completion time.
func (q *Queries) StampMissingChatTTLForEndedTrips(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, stampMissingChatTTLForEndedTrips, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChatSessionSummary = `-- name: UpdateChatSessionSummary :execrows
UPDATE chat_sessions
SET summary = $4, summary_message_count = $5
WHERE id = $1 AND user_id = $2 AND trip_id = $3
`

type UpdateChatSessionSummaryParams struct {
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
	TripID              string    `json:"trip_id"`
	Summary             string    `json:"summary"`
	SummaryMessageCount int32     `json:"summary_message_count"`
}

func (q *Queries) UpdateChatSessionSummary(ctx context.Context, arg UpdateChatSessionSummaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChatSessionSummary,
		arg.ID,
		arg.UserID,
		arg.TripID,
		arg.Summary,
		arg.SummaryMessageCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertChatSessionForMessage = `-- name: UpsertChatSessionForMessage :one
INSERT INTO chat_sessions (id, user_id, trip_id, mode, created_at, last_message_at, message_count)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $5,
    CASE WHEN $6::bool THEN 1 ELSE 0 END
)
ON CONFLICT (id) DO UPDATE SET
    last_message_at = EXCLUDED.last_message_at,
    message_count = chat_sessions.message_count
        + CASE WHEN $6::bool THEN 1 ELSE 0 END,
    mode = COALESCE(NULLIF($4::text, ''), chat_sessions.mode)
WHERE chat_sessions.user_id = EXCLUDED.user_id
  AND chat_sessions.trip_id = EXCLUDED.trip_id
RETURNING id
`

type UpsertChatSessionForMessageParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	TripID        string    `json:"trip_id"`
	Mode          string    `json:"mode"`
	LastMessageAt time.Time `json:"last_message_at"`
	CountMessage  bool      `json:"count_message"`
}

// UpsertChatSessionForMessage records message activity on a session,
// creating the session implicitly if the client passed an unknown session ID
// (mirrors the Firestore MergeAll upsert this port replaced). The WHERE guard
// refuses to touch a session that exists under a different user or trip —
// the caller treats the resulting no-row as "session not found".
func (q *Queries) UpsertChatSessionForMessage(ctx context.Context, arg UpsertChatSessionForMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertChatSessionForMessage,
		arg.ID,
		arg.UserID,
		arg.TripID,
		arg.Mode,
		arg.LastMessageAt,
		arg.CountMessage,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
