// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package dbgen

import (
	"context"
)

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE status = 'active'
`

func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsersLast7Days = `-- name: CountActiveUsersLast7Days :one
SELECT COUNT(DISTINCT user_id) FROM daily_usage WHERE date >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) CountActiveUsersLast7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersLast7Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesToday = `-- name: CountMessagesToday :one
SELECT COALESCE(SUM(message_count), 0)::bigint FROM daily_usage WHERE date = CURRENT_DATE
`

func (q *Queries) CountMessagesToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesToday)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProUsers = `-- name: CountProUsers :one
SELECT COUNT(*) FROM users WHERE subscription_tier = 'pro'
`

func (q *Queries) CountProUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsLast7Days = `-- name: CountSignupsLast7Days :one
SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) CountSignupsLast7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsLast7Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsToday = `-- name: CountSignupsToday :one
SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE
`

func (q *Queries) CountSignupsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalTrips = `-- name: CountTotalTrips :one
SELECT COUNT(*) FROM trips
`

func (q *Queries) CountTotalTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalTrips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripProPurchases = `-- name: CountTripProPurchases :one
SELECT COUNT(*) FROM payments
`

func (q *Queries) CountTripProPurchases(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTripProPurchases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSubscriptionsByTier = `-- name: GetActiveSubscriptionsByTier :many
SELECT tier, COUNT(*)::bigint AS sub_count
FROM subscriptions
WHERE status = 'active'
GROUP BY tier
`

type GetActiveSubscriptionsByTierRow struct {
	Tier     string `json:"tier"`
	SubCount int64  `json:"sub_count"`
}

func (q *Queries) GetActiveSubscriptionsByTier(ctx context.Context) ([]GetActiveSubscriptionsByTierRow, error) {
	rows, err := q.db.Query(ctx, getActiveSubscriptionsByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveSubscriptionsByTierRow{}
	for rows.Next() {
		var i GetActiveSubscriptionsByTierRow
		if err := rows.Scan(&i.Tier, &i.SubCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTripProRevenueCents = `-- name: GetMonthlyTripProRevenueCents :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint
FROM payments
WHERE status = 'approved' AND created_at >= CURRENT_DATE - INTERVAL '30 days'
`

func (q *Queries) GetMonthlyTripProRevenueCents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyTripProRevenueCents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalTripProRevenueCents = `-- name: GetTotalTripProRevenueCents :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint
FROM payments
WHERE status = 'approved'
`

func (q *Queries) GetTotalTripProRevenueCents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalTripProRevenueCents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
