// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package dbgen

import (
	"context"
)

const countSignupsLast7Days = `-- name: CountSignupsLast7Days :one
SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) CountSignupsLast7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsLast7Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsToday = `-- name: CountSignupsToday :one
SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE
`

func (q *Queries) CountSignupsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSignupsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalTrips = `-- name: CountTotalTrips :one
SELECT COUNT(*) FROM trips
`

func (q *Queries) CountTotalTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalTrips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
