// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, jti, family, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, jti, family, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Jti       string    `json:"jti"`
	Family    uuid.UUID `json:"family"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.Jti,
		arg.Family,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.Family,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshTokenByJTI = `-- name: GetRefreshTokenByJTI :one
SELECT id, user_id, jti, family, expires_at, revoked, created_at FROM refresh_tokens
WHERE jti = $1
`

func (q *Queries) GetRefreshTokenByJTI(ctx context.Context, jti string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByJTI, jti)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.Family,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByJTIForUpdate = `-- name: GetRefreshTokenByJTIForUpdate :one
SELECT id, user_id, jti, family, expires_at, revoked, created_at FROM refresh_tokens
WHERE jti = $1
FOR UPDATE
`

// Row-locks the refresh_tokens row for the duration of the enclosing
// transaction so concurrent RefreshToken RPCs serialize on rotation.
// Must be used inside a transaction; closes the TOCTOU window where two
// parallel refreshes with the same JTI could both observe revoked=false.
func (q *Queries) GetRefreshTokenByJTIForUpdate(ctx context.Context, jti string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByJTIForUpdate, jti)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.Family,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked = true
WHERE jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, jti)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked = true
WHERE family = $1
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, family uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, family)
	return err
}
